# Generated by Django 4.2.30 on 2026-07-14 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_type', models.CharField(choices=[('leave', '请假'), ('overtime', '加班'), ('expense', '报销'), ('trip', '出差'), ('purchase', '采购'), ('other', '其他')], max_length=20, verbose_name='审批类型')),
                ('title', models.CharField(max_length=200, verbose_name='审批标题')),
                ('content', models.TextField(blank=True, default='', verbose_name='审批内容')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已通过'), ('rejected', '已驳回'), ('cancelled', '已撤回')], db_index=True, default='pending', max_length=20, verbose_name='审批状态')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('duration', models.FloatField(blank=True, null=True, verbose_name='天数')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='金额')),
                ('approver_comment', models.TextField(blank=True, default='', verbose_name='审批意见')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_tasks', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
            ],
            options={
                'verbose_name': '审批请求',
                'verbose_name_plural': '审批请求',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('approve', '通过'), ('reject', '驳回')], max_length=20, verbose_name='操作')),
                ('comment', models.TextField(blank=True, default='', verbose_name='操作意见')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='oa.approvalrequest', verbose_name='审批请求')),
            ],
            options={
                'verbose_name': '审批日志',
                'verbose_name_plural': '审批日志',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clock_type', models.CharField(choices=[('clock_in', '上班打卡'), ('clock_out', '下班打卡')], max_length=20, verbose_name='打卡类型')),
                ('clock_time', models.DateTimeField(auto_now_add=True, verbose_name='打卡时间')),
                ('date', models.DateField(db_index=True, verbose_name='打卡日期')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='纬度')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='经度')),
                ('location', models.CharField(blank=True, default='', max_length=255, verbose_name='打卡位置')),
                ('device', models.CharField(blank=True, default='', max_length=100, verbose_name='打卡设备')),
                ('status', models.CharField(choices=[('normal', '正常'), ('late', '迟到'), ('early_leave', '早退')], default='normal', max_length=20, verbose_name='打卡状态')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '打卡记录',
                'verbose_name_plural': '打卡记录',
                'ordering': ['-clock_time'],
                'indexes': [models.Index(fields=['user', 'date'], name='oa_attendan_user_id_590923_idx'), models.Index(fields=['date'], name='oa_attendan_date_619b53_idx')],
            },
        ),
    ]
