# Generated by Django 4.2.30 on 2026-07-15 05:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_consultationrequest'),
        ('oa', '0002_add_expense_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalrequest',
            name='approval_mode',
            field=models.CharField(choices=[('sequential', '顺序审批'), ('parallel', '并行审批')], default='parallel', max_length=20, verbose_name='审批模式'),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='current_node_order',
            field=models.IntegerField(default=0, verbose_name='当前节点序号'),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='sign_type',
            field=models.CharField(choices=[('countersign', '会签'), ('orsign', '或签')], default='orsign', max_length=20, verbose_name='审批方式'),
        ),
        migrations.CreateModel(
            name='ApprovalNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_type', models.CharField(choices=[('user', '指定用户'), ('department', '指定部门')], max_length=20, verbose_name='节点类型')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_node_departments', to='accounts.department', verbose_name='审批部门')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_nodes', to='oa.approvalrequest', verbose_name='审批请求')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_node_users', to=settings.AUTH_USER_MODEL, verbose_name='审批用户')),
            ],
            options={
                'verbose_name': '审批节点',
                'verbose_name_plural': '审批节点',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalAssignee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已通过'), ('rejected', '已驳回')], default='pending', max_length=20, verbose_name='审批状态')),
                ('comment', models.TextField(blank=True, default='', verbose_name='审批意见')),
                ('operated_at', models.DateTimeField(blank=True, null=True, verbose_name='操作时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignees', to='oa.approvalnode', verbose_name='审批节点')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_assignees', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
            ],
            options={
                'verbose_name': '审批人',
                'verbose_name_plural': '审批人',
                'ordering': ['id'],
            },
        ),
    ]
