# Generated by Django 4.2.30 on 2026-07-15 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oa', '0003_approvalrequest_approval_mode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('approval', '审批通知'), ('attendance', '考勤通知'), ('task', '任务通知'), ('system', '系统通知')], max_length=20, verbose_name='通知类型')),
                ('title', models.CharField(max_length=200, verbose_name='通知标题')),
                ('content', models.TextField(blank=True, default='', verbose_name='通知内容')),
                ('related_url', models.CharField(blank=True, default='', max_length=500, verbose_name='相关链接')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='是否已读')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('extra_data', models.JSONField(blank=True, null=True, verbose_name='扩展数据')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='接收人')),
            ],
            options={
                'verbose_name': '工作通知',
                'verbose_name_plural': '工作通知',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='oa_worknoti_recipie_0cf076_idx'), models.Index(fields=['recipient', '-created_at'], name='oa_worknoti_recipie_fe4929_idx')],
            },
        ),
    ]
