# Generated by Django 4.2.30 on 2026-07-16 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oa', '0004_worknotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='reverse_geocoding',
            field=models.JSONField(blank=True, null=True, verbose_name='反地理编码结果'),
        ),
    ]
