# Generated by Django 4.2.30 on 2026-07-17 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oa', '0005_attendancerecord_reverse_geocoding'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='bd09_latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='BD09纬度'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='bd09_longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='BD09经度'),
        ),
        migrations.AlterField(
            model_name='worknotification',
            name='notification_type',
            field=models.CharField(choices=[('approval', '审批通知'), ('attendance', '考勤通知'), ('task', '任务通知'), ('collab', '协作通知'), ('system', '系统通知')], max_length=20, verbose_name='通知类型'),
        ),
    ]
