# Generated by Django 4.2.30 on 2026-07-17 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oa', '0006_attendancerecord_bd09_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='ip_address',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='IP地址'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='user_agent',
            field=models.TextField(blank=True, default='', verbose_name='User-Agent'),
        ),
    ]
