# Generated by Django 4.2.30 on 2026-07-17 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oa', '0007_attendancerecord_ip_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalrequest',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('pending', '待审批'), ('approved', '已通过'), ('rejected', '已驳回'), ('cancelled', '已撤回')], db_index=True, default='pending', max_length=20, verbose_name='审批状态'),
        ),
    ]
