# Generated by Django 4.2.30 on 2026-07-18 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oa', '0008_alter_approvalrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvallog',
            name='action',
            field=models.CharField(choices=[('approve', '通过'), ('reject', '驳回'), ('resubmit', '重新提交')], max_length=20, verbose_name='操作'),
        ),
    ]
