# Generated by Django 4.2.30 on 2026-07-18 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oa', '0009_alter_approvallog_action'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approvallog',
            options={'ordering': ['-created_at'], 'verbose_name': '审批日志', 'verbose_name_plural': '审批日志'},
        ),
        migrations.AlterField(
            model_name='approvallog',
            name='action',
            field=models.CharField(choices=[('approve', '通过'), ('reject', '驳回'), ('resubmit', '重新提交'), ('cancel', '撤回')], max_length=20, verbose_name='操作'),
        ),
    ]
