# Generated by Django 3.2.25 on 2026-07-30 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0006_auto_20260730_1521'),
        ('oa', '0010_alter_approvallog_options_alter_approvallog_action'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approvalassignee',
            options={'ordering': ['-id'], 'verbose_name': '审批人', 'verbose_name_plural': '审批人'},
        ),
        migrations.AlterModelOptions(
            name='approvalnode',
            options={'ordering': ['-order', '-id'], 'verbose_name': '审批节点', 'verbose_name_plural': '审批节点'},
        ),
        migrations.AlterModelOptions(
            name='approvalrequest',
            options={'ordering': ['-updated_at'], 'verbose_name': '审批请求', 'verbose_name_plural': '审批请求'},
        ),
        migrations.AddField(
            model_name='approvallog',
            name='attachments',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='附件'),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='recruit_data',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='招聘需求数据'),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='accounts.tenant', verbose_name='所属企业'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='accounts.tenant', verbose_name='所属企业'),
        ),
        migrations.AddField(
            model_name='worknotification',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.tenant', verbose_name='所属企业'),
        ),
        migrations.AlterField(
            model_name='approvalassignee',
            name='status',
            field=models.CharField(choices=[('pending', '待审批'), ('approved', '已通过'), ('rejected', '已驳回'), ('deferred', '暂缓'), ('processing', '办理中')], default='pending', max_length=20, verbose_name='审批状态'),
        ),
        migrations.AlterField(
            model_name='approvallog',
            name='action',
            field=models.CharField(choices=[('approve', '通过'), ('reject', '驳回'), ('defer', '暂缓'), ('processing', '正在办理'), ('resubmit', '重新提交'), ('cancel', '撤回')], max_length=20, verbose_name='操作'),
        ),
        migrations.AlterField(
            model_name='approvalrequest',
            name='approval_type',
            field=models.CharField(choices=[('leave', '请假'), ('overtime', '加班'), ('expense', '报销'), ('trip', '出差'), ('purchase', '采购'), ('recruit', '招聘需求'), ('other', '其他')], max_length=20, verbose_name='审批类型'),
        ),
        migrations.AlterField(
            model_name='approvalrequest',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('pending', '待审批'), ('approved', '已通过'), ('rejected', '已驳回'), ('deferred', '暂缓'), ('processing', '办理中'), ('cancelled', '已撤回')], db_index=True, default='pending', max_length=20, verbose_name='审批状态'),
        ),
        migrations.CreateModel(
            name='ApprovalCarbonCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cc_type', models.CharField(choices=[('user', '用户'), ('department', '部门')], default='user', max_length=20, verbose_name='抄送类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('cc_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_ccs', to='accounts.department', verbose_name='抄送部门')),
                ('cc_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_ccs', to=settings.AUTH_USER_MODEL, verbose_name='抄送人')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carbon_copies', to='oa.approvalrequest', verbose_name='审批请求')),
            ],
            options={
                'verbose_name': '审批抄送',
                'verbose_name_plural': '审批抄送',
            },
        ),
        migrations.CreateModel(
            name='AttendanceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clock_in_enabled', models.BooleanField(default=True, verbose_name='启用上班打卡')),
                ('clock_in_time', models.TimeField(blank=True, null=True, verbose_name='上班打卡截止时间')),
                ('clock_out_enabled', models.BooleanField(default=True, verbose_name='启用下班打卡')),
                ('clock_out_time', models.TimeField(blank=True, null=True, verbose_name='下班打卡开始时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_configs', to='accounts.department', verbose_name='部门')),
                ('sub_tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_attendance_configs', to='accounts.tenant', verbose_name='子公司')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_configs', to='accounts.tenant', verbose_name='所属企业')),
            ],
            options={
                'verbose_name': '考勤配置',
                'verbose_name_plural': '考勤配置',
                'unique_together': {('tenant', 'sub_tenant', 'department')},
            },
        ),
        migrations.CreateModel(
            name='ApprovalDeptConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_type', models.CharField(choices=[('leave', '请假'), ('overtime', '加班'), ('expense', '报销'), ('trip', '出差'), ('purchase', '采购'), ('recruit', '招聘需求'), ('other', '其他')], max_length=20, verbose_name='审批类型')),
                ('default_sign_type', models.CharField(choices=[('countersign', '会签'), ('orsign', '或签')], default='countersign', max_length=20, verbose_name='默认审批方式')),
                ('default_approval_mode', models.CharField(choices=[('sequential', '顺序审批'), ('parallel', '并行审批')], default='sequential', max_length=20, verbose_name='默认审批模式')),
                ('cc_departments', models.JSONField(blank=True, default=list, verbose_name='默认抄送部门ID列表')),
                ('cc_users', models.JSONField(blank=True, default=list, verbose_name='默认抄送人ID列表')),
                ('approver_users', models.JSONField(blank=True, default=list, verbose_name='默认审批人ID列表')),
                ('threshold_enabled', models.BooleanField(default=False, verbose_name='启用阈值审批')),
                ('threshold_field', models.CharField(blank=True, choices=[('duration', '天数/时长'), ('amount', '金额'), ('headcount', '招聘人数')], default='', help_text='根据审批类型选择：请假/出差选天数，报销/采购选金额，招聘选人数', max_length=30, verbose_name='阈值字段')),
                ('threshold_value', models.FloatField(blank=True, null=True, verbose_name='阈值')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.department', verbose_name='最终审批部门')),
                ('sub_tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_approval_dept_configs', to='accounts.tenant', verbose_name='子公司')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_dept_configs', to='accounts.tenant', verbose_name='所属企业')),
                ('threshold_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='threshold_approval_configs', to='accounts.department', verbose_name='阈值超额后最终审批部门')),
            ],
            options={
                'verbose_name': '审批类型配置',
                'verbose_name_plural': '审批类型配置',
                'unique_together': {('tenant', 'approval_type', 'sub_tenant')},
            },
        ),
    ]
