# -*- coding: utf-8 -*-
from django.core.management.base import BaseCommand
import os
import base64


class Command(BaseCommand):
    help = '生成 Web Push VAPID 密钥对（写入 .env，需手动追加到 settings）'

    def handle(self, *args, **options):
        # 直接用 cryptography 生成 EC P-256 密钥对（cryptography 随 pywebpush 自动安装），
        # 不依赖 py_vapid 的版本相关 API（旧版 public_key_b64url / 新版 Vapid02 已移除）。
        try:
            from cryptography.hazmat.primitives.asymmetric import ec
            from cryptography.hazmat.primitives import serialization
        except ImportError:
            self.stderr.write('未安装 cryptography，请先执行 pip install cryptography')
            return

        key = ec.generate_private_key(ec.SECP256R1())
        pub = key.public_key()

        # public: X9.62 未压缩点（65 字节），private: 32 字节私钥标量，均 base64url 无填充
        pub_b64 = base64.urlsafe_b64encode(
            pub.public_bytes(serialization.Encoding.X962, serialization.PublicFormat.UncompressedPoint)
        ).rstrip(b'=').decode()
        priv_b64 = base64.urlsafe_b64encode(
            key.private_numbers().private_value.to_bytes(32, 'big')
        ).rstrip(b'=').decode()

        self.stdout.write(self.style.SUCCESS('=== VAPID 密钥生成成功 ==='))
        self.stdout.write(f'VAPID_PUBLIC_KEY={pub_b64}')
        self.stdout.write(f'VAPID_PRIVATE_KEY={priv_b64}')
        self.stdout.write('VAPID_ADMIN_EMAIL=admin@first-iq.com')
        # 尝试写入 .env（若已有 VAPID 密钥则跳过，避免追加重复导致 decouple 解析冲突）
        env_path = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))), '.env')
        if os.path.exists(env_path):
            try:
                with open(env_path, 'r', encoding='utf-8') as f:
                    existing = f.read()
                if 'VAPID_PUBLIC_KEY' in existing and 'VAPID_PRIVATE_KEY' in existing:
                    self.stdout.write(self.style.WARNING(
                        '检测到 .env 中已存在 VAPID 密钥，跳过写入（保留现有密钥，直接使用即可）'))
                    return
                with open(env_path, 'a', encoding='utf-8') as f:
                    f.write("\n# Web Push VAPID keys (generated by gen_vapid_keys)\n")
                    f.write(f"VAPID_PUBLIC_KEY={pub_b64}\n")
                    f.write(f"VAPID_PRIVATE_KEY={priv_b64}\n")
                    f.write("VAPID_ADMIN_EMAIL=admin@first-iq.com\n")
                self.stdout.write(self.style.SUCCESS(f'已写入 {env_path}'))
            except Exception as e:
                self.stderr.write(f'写入 .env 失败（请手动追加）: {e}')
        else:
            self.stdout.write('未找到 .env，请将上面的密钥手动加入配置')
