"""
Django settings for company_chat project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import sys
import os
from decouple import config
from datetime import timedelta
import re
import datetime

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-fz(25n_*5fk$glzg%mh_imzritgz4_syd5nls3x1u3-3o*j4y-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = config('ALLOWED_HOSTS', cast=lambda x: x.split(',')) or ['*']

# 必须在 INSTALLED_APPS 之前设置
AUTH_USER_MODEL = 'accounts.CustomUser'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',  # 必须保留，提供认证框架
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'django_celery_beat',

    # Third party apps
    'rest_framework',
    'channels',
    'corsheaders',

    # Local apps - accounts 必须在 chat 之前
    'accounts',  # 自定义用户模型应用
    'chat',
    'cloud',
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",  # 跨域中间件
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # 👈 补充这行
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # 'cloud.middleware.OnlyOfficeMiddleware',  # 🔧 添加这行
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'accounts.middleware.ApiLoggingMiddleware',
    # 'chat.middleware.SystemConfigCacheMiddleware',  # 🔧 添加配置缓存中间件
]

INSTALLED_APPS += ['debug_toolbar']
MIDDLEWARE.insert(0, 'debug_toolbar.middleware.DebugToolbarMiddleware')

ROOT_URLCONF = 'company_chat.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'company_chat.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

if sys.platform == 'linux':

    DATABASES = {
        # 'default': {
        #     'ENGINE': 'django.db.backends.sqlite3',
        #     'NAME': BASE_DIR / 'db.sqlite3',
        # }
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': config('DB_NAME'),
            'USER': config('DB_USER'),
            'PASSWORD': config('DB_PASSWORD'),
            'HOST': config('DB_HOST'),
            'PORT': config('DB_PORT'),
            'CONN_MAX_AGE': config('CONN_MAX_AGE', default=60, cast=int),
            # 'CONN_MAX_AGE': 60,  # 连接最大存活时间（秒）
            'CONN_HEALTH_CHECKS': True,  # 连接健康检查
            'OPTIONS': {
                'connect_timeout': 10,
                'options': '-c statement_timeout=30000',
                'keepalives': 1,  # 启用 TCP Keepalive
                'keepalives_idle': 30,  # 空闲 30 秒后发送探测包
                # ❌ 删除 pool_size 和 max_overflow（psycopg2 不支持）
                # 'pool_size': 10,
                # 'max_overflow': 20,
            },

        }
    }

    # redis 配置
    REDIS_HOST = config('REDIS_HOST')
    REDIS_PASSWORD = config('REDIS_PASSWORD')
    REDIS_PORT = config('REDIS_PORT', default=6379, cast=int)

    # 生产/Linux 环境：尝试使用 WhiteNoise，失败则自动降级
    # try:
    #     import whitenoise
    #
    #     STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
    # except ImportError:
    #     STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.ManifestStaticFilesStorage'

else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

    # redis 配置
    REDIS_HOST = '127.0.0.1'
    REDIS_PASSWORD = 'dayue123456'
    REDIS_PORT = 6379

    # 开发/Windows/macOS 环境：使用默认存储
    STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'

# REDIS_LOCATION = f"redis://:{REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT}"
REDIS_LOCATION = f"redis://{REDIS_HOST}:{REDIS_PORT}"

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'chat.consumers': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'channels': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

# ASGI application
ASGI_APPLICATION = 'company_chat.asgi.application'

# 安装 django-redis
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",  # ✅ 使用 django-redis
        "LOCATION": f"redis://{REDIS_HOST}:{REDIS_PORT}/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            # ✅ 连接池配置（django-redis 支持 CONNECTION_POOL_KWARGS）
            "CONNECTION_POOL_KWARGS": {
                "max_connections": 100,
                "retry_on_timeout": True,
                "socket_connect_timeout": 5,
                "socket_timeout": 5,
                "health_check_interval": 30,
            },
            # ✅ 序列化
            "SERIALIZER": "django_redis.serializers.json.JSONSerializer",
        },
        "KEY_PREFIX": "company_chat",
        "TIMEOUT": 300,
    }
}

# 🔧 确保 Channels 使用独立的 Redis 数据库（避免缓存键冲突）
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            # ✅ 使用数据库 2，与 CACHES 的数据库 1 分离
            "hosts": [f"redis://{REDIS_HOST}:{REDIS_PORT}/2"],
            "capacity": 1500,  # 默认 100
            "expiry": 10,  # 默认 60 秒
            "prefix": "asgi",
            # "close_timeout": 10,  # 增加到 10 秒
            # "pool_size": 20,  # ✅ 连接池大小, 报错
        },
    },
}

celery_redis_host = config('CELERY_REDIS_HOST')
celery_redis_port = config('CELERY_REDIS_PORT')
celery_redis_password = config('CELERY_REDIS_PASSWORD')
ENABLE_LOGIN_ANALYSIS_LOG = True
# CELERY_REDIS_LOCATION = f"redis://:{celery_redis_password}@{celery_redis_host}:{celery_redis_port}/3"
CELERY_REDIS_LOCATION = f"redis://{celery_redis_host}:{celery_redis_port}/3"

# Celery 配置
CELERY_BROKER_URL = f'{CELERY_REDIS_LOCATION}'
CELERY_RESULT_BACKEND = f'{CELERY_REDIS_LOCATION}'
CELERY_TIMEZONE = "Asia/Shanghai"
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# 添加这些关键配置
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_ENABLE_UTC = False

AES_KEY = config('AES_KEY')
SM4_KEY = config('SM4_KEY')

KEEP_DAYS = config('KEEP_DAYS', default=15, cast=int)

# WebSocket 超时配置
WEBSOCKET_CONNECT_TIMEOUT = 30  # 连接超时（秒）
WEBSOCKET_DISCONNECT_TIMEOUT = 10  # 断开超时（秒）

# REST Framework配置
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    # ❌ 错误：全局要求认证
    # 'DEFAULT_PERMISSION_CLASSES': (
    #     'rest_framework.permissions.IsAuthenticated',
    # ),

    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
}

# JWT 配置
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=8),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}

# CORS配置
CORS_ALLOW_ALL_ORIGINS = True  # 生产环境应限制为具体域名

# 认证后端
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# ================================================= #
# ******************* 跨域的配置 ******************* #
# ================================================= #

# 允许所有来源（仅用于开发环境）
# CORS_ALLOW_ALL_ORIGINS = True

# 或者指定允许的前端地址（推荐用于生产环境）
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",  # 前端地址
    "http://192.168.20.33:5173",  # 前端地址
    "http://chat.first-iq.com:10900",  # 前端地址
    "http://chat.first-iq.com:10901",  # 前端地址
    "https://chat.first-iq.com",  # 前端地址
    "http://onlyoffice.first-iq.com",  # OnlyOffice 域名
    "http://onlyoffice.first-iq.com:12280",  # OnlyOffice 域名
    "http://192.168.1.122",  # OnlyOffice 可选，直接 IP 访问
    "http://192.168.1.122:8000",  # OnlyOffice
    "http://192.168.1.130",  # Django
    "http://192.168.1.130:10900",  # Django
]

# 指定允许的后端地址（推荐用于生产环境）
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",  # 前端地址
    "http://192.168.20.33:5173",  # 前端地址
    "http://chat.first-iq.com:10900",
    "http://chat.first-iq.com:10901",  # 前端地址
    "https://chat.first-iq.com",  # 前端地址
    "http://onlyoffice.first-iq.com",  # OnlyOffice 域名
    "http://onlyoffice.first-iq.com:12280",  # OnlyOffice 域名
    # Add other trusted origins if needed
]

# 暴露自定义头,否则前端无法获取自定义头
CORS_EXPOSE_HEADERS = ['Captcha-Key', 'Content-Disposition']

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

# LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC'

# Internationalization
LANGUAGE_CODE = 'zh-hans'
TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

# STATIC_URL = '/static/'
# STATICFILES_DIRS = [BASE_DIR / 'static']
# STATIC_ROOT = BASE_DIR / 'staticfiles'
#
# MEDIA_URL = '/media/'
# MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'

if sys.platform == 'linux':

    STATIC_URL = 'static/'
    STATIC_ROOT = BASE_DIR / 'static'

    # 素材上传配置
    MEDIA_URL = 'media/'
    MEDIA_ROOT = BASE_DIR / 'media'
else:
    # 静态文件配置
    STATIC_URL = '/static/'
    STATICFILES_DIRS = [
        os.path.join(BASE_DIR, 'static'),  # 前端静态资源目录
    ]
    STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # collectstatic 收集目录

    # 多媒体文件配置（用户上传的文件）
    MEDIA_URL = '/media/'
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')  # 上传文件存储目录

    # 确保 media 目录存在
    if not os.path.exists(MEDIA_ROOT):
        os.makedirs(MEDIA_ROOT)

BASE_URL = 'https://chat.first-iq.com/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 静态文件版本（每次部署更新）
STATIC_VERSION = '20260606-55ec1e7'

# 构建时间
BUILD_TIME = str(datetime.datetime.now())[:19]

# # 静态文件存储（生产环境使用 WhiteNoise 或 CDN）
# STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# # WhiteNoise 配置
# WHITENOISE_MAX_AGE = 31536000  # 1年
# WHITENOISE_IMMUTABLE_FILE_TEST = lambda path, url: re.match(r'^.+\.[0-9a-f]{12}\..+$', url)


API_LOG_ENABLE = True
# API_LOG_METHODS = 'ALL' # ['POST', 'DELETE']
API_LOG_METHODS = ["POST", "UPDATE", "DELETE", "PUT", 'PATCH']  # ['POST', 'DELETE']
API_MODEL_MAP = {
    "/api/auth/profile/": "个人资料",
    "/api/auth/login/": "登录",
    "/api/auth/logout/": "登出",
    "/api/chat/upload/": "文件管理",
    "/api/chat/rooms/": "聊天室管理",
    "/api/chat/messages/": "消息管理",
    "/api/auth/admin/users/": "用户管理",
}
EXLUDE_API_LOG = [
    "/api/chat/messages/mark_as_read/"  # 标记已读
]
API_METHOD_MAP = {
    'GET': '查询',
    'POST': '新建',
    'PUT': '更新',
    'OPTIONS': '查询',
    'HEAD': '查询',
    'UPDATE': '修改',
    'DELETE': '删除',
    'PATCH': '修改',
}

# ================================================= #
# ******************* 邮箱配置 ******************* #
# ================================================= #
# smtp后端,默认配置
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# 控制台后端开发时使用
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

EMAIL_HOST = config('EMAIL_HOST')
EMAIL_PORT = config('EMAIL_PORT', default=465, cast=int)
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
DEFAULT_FROM_EMAIL = config('EMAIL_FROM_EMAIL')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
EMAIL_USE_SSL = config('EMAIL_USE_SSL', default=True, cast=bool)
# EMAIL_FROM_EMAIL = config('EMAIL_FROM_EMAIL')
EMAIL_SUBJECT_PREFIX = config('EMAIL_SUBJECT_PREFIX')
EMAIL_TIMEOUT = config('EMAIL_TIMEOUT', default=300, cast=int)  # 超时(5分钟)

PASSWORD_RESET_TOKEN_EXPIRES_MINUTES = config('PASSWORD_RESET_TOKEN_EXPIRES_MINUTES', default=20, cast=int)
PASSWORD_RESET_TOKEN_EXPIRES_HOURS = config('PASSWORD_RESET_TOKEN_EXPIRES_HOURS', default=1, cast=int)

# 前端地址（用于生成重置链接）
FRONTEND_URL = config('FRONTEND_URL', default='https://chat.first-iq.com', cast=str)

# LOGGING = {
#     'version': 1,
#     'disable_existing_loggers': False,
#     'handlers': {
#         'console': {
#             'class': 'logging.StreamHandler',
#         },
#         'file': {
#             'class': 'logging.FileHandler',
#             'filename': '/www/yue/company_chat/logs/onlyoffice.log',
#         },
#     },
#     'loggers': {
#         'cloud.views': {
#             'handlers': ['console', 'file'],
#             'level': 'DEBUG',
#             'propagate': False,
#         },
#     },
# }


# # 🔧 OnlyOffice 配置
# ONLYOFFICE_URL = 'http://localhost:8080'  # OnlyOffice Document Server 地址
# ONLYOFFICE_SECRET = 'your-secret-key'  # JWT 密钥
# ONLYOFFICE_SERVER_URL = 'https://chat.first-iq.com/cloud/'  # 企业网盘地址
#
# # 文档版本保留策略
# DOCUMENT_VERSION_KEEP_COUNT = 10  # 保留最近 10 个版本
# DOCUMENT_VERSION_KEEP_DAYS = 30  # 保留 30 天
#
# # 编辑锁过期时间（分钟）
# DOCUMENT_EDIT_LOCK_EXPIRE_MINUTES = 30

# 🔧 OnlyOffice 配置
ONLYOFFICE = {
    # 🔧 Document Server 地址（服务器 2）
    # 'DOCUMENT_SERVER_URL': 'http://192.168.1.122:8000',
    # 'DOCUMENT_SERVER_URL': 'http://onlyoffice.first-iq.com:12280',
    'DOCUMENT_SERVER_URL': 'https://chat.first-iq.com/onlyoffice',

    # 🔧 企业网盘地址（服务器 1，OnlyOffice 会回调这个地址）
    # 必须是 OnlyOffice 服务器能访问的地址
    # 'SERVER_URL': 'http://192.168.1.130:10900',
    'SERVER_URL': 'https://chat.first-iq.com',
    'CLOUD_SERVER_URL': 'https://chat.first-iq.com/cloud/',

    # 🔧 JWT 密钥（必须与服务器 2 的 JWT_SECRET 完全一致）
    'JWT_SECRET': config('JWT_SECRET'),

    # 是否启用 JWT
    'JWT_ENABLED': True,

    # JWT Header
    'JWT_HEADER': 'Authorization',

    # 支持的文件格式
    'WORD_FORMATS': ['.doc', '.docx', '.docm', '.dot', '.dotx', '.dotm', '.odt', '.ott', '.rtf', '.txt',
                     '.html', '.htm', '.mht', '.pdf', '.fb2', '.epub', '.xps',
                     ],
    'EXCEL_FORMATS': ['.xls', '.xlsx', '.xlsm', '.xlt', '.xltx', '.xltm', '.ods', '.ots', '.csv', ],
    'PPT_FORMATS': ['.pps', '.ppsx', '.ppsm', '.ppt', '.pptx', '.pptm', '.pot', '.potx', '.potm', '.odp', '.otp', ],
    'PDF_FORMATS': ['.pdf'],

    # 🔧 新增：文档版本和编辑锁配置
    'VERSION_KEEP_COUNT': 10,  # 保留最近 10 个版本
    'VERSION_KEEP_DAYS': 30,  # 保留 30 天
    'EDIT_LOCK_EXPIRE_MINUTES': 30,  # 编辑锁过期时间（分钟）

    # 🔧 聊天相关配置
    'CHAT_ENABLED': True,
    'CHAT_HISTORY_LIMIT': 100,
}

CHANNELS_ENABLED = True

# CORS_ALLOW_CREDENTIALS = True


# 聊天室系统设置

CACHE_PREFIX = 'company_chat:config:'  # ✅ 添加前缀避免冲突

# 🔧 预定义配置项（企业级聊天室核心配置）
PREDEFINED_CONFIGS = {
    # ==================== 基础设置 ====================
    'system.name': {
        'name': '系统名称',
        'value_type': 'string',
        'default': '企业聊天室',
        'description': '显示在页面标题和登录页的系统名称',
        'category': 'basic',
        'validation': {'min_length': 2, 'max_length': 50}
    },
    'system.logo_url': {
        'name': '系统 Logo',
        'value_type': 'string',
        'default': '/static/images/logo.png',
        'description': '系统标识图片的 URL 地址',
        'category': 'basic',
        'validation': {'pattern': r'^https?://.*\.(png|jpg|jpeg|svg)$'}
    },
    'system.maintenance_mode': {
        'name': '维护模式',
        'value_type': 'boolean',
        'default': 'false',
        'description': '开启后普通用户无法访问，仅管理员可用',
        'category': 'basic'
    },
    'system.user_registration_enabled': {
        'name': '用户注册',
        'value_type': 'boolean',
        'default': 'false',
        'description': '是否允许新用户自主注册',
        'category': 'basic'
    },
    'system.default_language': {
        'name': '默认语言',
        'value_type': 'string',
        'default': 'zh-CN',
        'description': '新用户默认界面语言',
        'category': 'basic',
        'choices': ['zh-CN', 'en-US', 'ja-JP']
    },
    'system.timezone': {
        'name': '默认时区',
        'value_type': 'string',
        'default': 'Asia/Shanghai',
        'description': '新用户默认时区设置',
        'category': 'basic'
    },

    # ==================== 聊天设置 ====================
    'chat.max_message_length': {
        'name': '消息最大长度',
        'value_type': 'integer',
        'default': '2000',
        'description': '单条消息允许的最大字符数',
        'category': 'chat',
        'validation': {'min': 100, 'max': 10000}
    },
    'chat.typing_timeout': {
        'name': '输入状态超时',
        'value_type': 'integer',
        'default': '5',
        'description': '输入状态显示超时时间（秒）',
        'category': 'chat',
        'validation': {'min': 1, 'max': 30}
    },
    'chat.message_retention_days': {
        'name': '消息保留天数',
        'value_type': 'integer',
        'default': '365',
        'description': '消息自动清理保留天数（0=永久保留）',
        'category': 'chat',
        'validation': {'min': 0, 'max': 3650}
    },
    'chat.read_receipt_enabled': {
        'name': '已读回执',
        'value_type': 'boolean',
        'default': 'true',
        'description': '是否显示消息已读状态',
        'category': 'chat'
    },
    'chat.history_sync_enabled': {
        'name': '历史消息同步',
        'value_type': 'boolean',
        'default': 'true',
        'description': '新设备登录时是否同步历史消息',
        'category': 'chat'
    },
    'chat.emoji_enabled': {
        'name': '表情功能',
        'value_type': 'boolean',
        'default': 'true',
        'description': '是否启用表情发送功能',
        'category': 'chat'
    },

    # ==================== 文件设置 ====================
    'file.max_upload_size_mb': {
        'name': '文件上传总上限',
        'value_type': 'integer',
        'default': '50',
        'description': '单个文件允许的最大上传大小（MB）',
        'category': 'file',
        'validation': {'min': 1, 'max': 1024}
    },
    'file.image_max_size_mb': {
        'name': '图片大小上限',
        'value_type': 'integer',
        'default': '20',
        'description': '图片文件允许的最大大小（MB）',
        'category': 'file',
        'validation': {'min': 1, 'max': 500}
    },
    'file.video_max_size_mb': {
        'name': '视频大小上限',
        'value_type': 'integer',
        'default': '100',
        'description': '视频文件允许的最大大小（MB）',
        'category': 'file',
        'validation': {'min': 10, 'max': 2048}
    },
    'file.audio_max_size_mb': {
        'name': '音频大小上限',
        'value_type': 'integer',
        'default': '30',
        'description': '音频文件允许的最大大小（MB）',
        'category': 'file',
        'validation': {'min': 1, 'max': 500}
    },
    'file.allowed_types': {
        'name': '允许的文件类型',
        'value_type': 'json',
        'default': '["image", "video", "audio", "file"]',
        'description': '允许上传的文件类型列表',
        'category': 'file',
        'validation': {'is_array': True}
    },
    'file.image_formats': {
        'name': '允许的图片格式',
        'value_type': 'json',
        'default': '["jpg", "jpeg", "png", "gif", "webp"]',
        'description': '允许上传的图片文件格式',
        'category': 'file'
    },
    'file.video_formats': {
        'name': '允许的视频格式',
        'value_type': 'json',
        'default': '["mp4", "webm", "mov"]',
        'description': '允许上传的视频文件格式',
        'category': 'file'
    },

    # ==================== 语音设置 ====================
    'voice.max_duration_seconds': {
        'name': '语音消息最大时长',
        'value_type': 'integer',
        'default': '60',
        'description': '语音消息允许的最大录制时长（秒）',
        'category': 'voice',
        'validation': {'min': 10, 'max': 300}
    },
    'voice.min_duration_seconds': {
        'name': '语音消息最小时长',
        'value_type': 'integer',
        'default': '1',
        'description': '语音消息允许的最小录制时长（秒）',
        'category': 'voice',
        'validation': {'min': 1, 'max': 10}
    },
    'voice.allowed_formats': {
        'name': '语音格式',
        'value_type': 'json',
        'default': '["webm", "mp3", "m4a", "ogg"]',
        'description': '允许的语音文件格式',
        'category': 'voice'
    },
    'voice.auto_transcribe': {
        'name': '语音转文字',
        'value_type': 'boolean',
        'default': 'false',
        'description': '是否自动将语音消息转换为文字',
        'category': 'voice'
    },

    # ==================== 安全设置 ====================
    'security.login_max_attempts': {
        'name': '登录最大尝试次数',
        'value_type': 'integer',
        'default': '5',
        'description': '连续登录失败最大次数后锁定账户',
        'category': 'security',
        'validation': {'min': 3, 'max': 20}
    },
    'security.login_lockout_minutes': {
        'name': '登录锁定时间',
        'value_type': 'integer',
        'default': '15',
        'description': '登录失败锁定账户的时长（分钟）',
        'category': 'security',
        'validation': {'min': 5, 'max': 1440}
    },
    'security.session_timeout_hours': {
        'name': '会话超时时间',
        'value_type': 'integer',
        'default': '24',
        'description': '用户会话无操作超时时间（小时）',
        'category': 'security',
        'validation': {'min': 1, 'max': 168}
    },
    'security.password_min_length': {
        'name': '密码最小长度',
        'value_type': 'integer',
        'default': '8',
        'description': '用户密码要求的最小长度',
        'category': 'security',
        'validation': {'min': 6, 'max': 32}
    },
    'security.password_require_special': {
        'name': '密码特殊字符',
        'value_type': 'boolean',
        'default': 'true',
        'description': '密码是否必须包含特殊字符',
        'category': 'security'
    },
    'security.sensitive_words': {
        'name': '敏感词过滤',
        'value_type': 'json',
        'default': '[]',
        'description': '消息内容敏感词列表（正则表达式）',
        'category': 'security',
        'validation': {'is_array': True}
    },

    # ==================== 通知设置 ====================
    'notification.desktop_enabled': {
        'name': '桌面通知',
        'value_type': 'boolean',
        'default': 'true',
        'description': '是否启用浏览器桌面通知',
        'category': 'notification'
    },
    'notification.sound_enabled': {
        'name': '声音提醒',
        'value_type': 'boolean',
        'default': 'true',
        'description': '是否启用新消息声音提醒',
        'category': 'notification'
    },
    'notification.vibrate_enabled': {
        'name': '震动提醒',
        'value_type': 'boolean',
        'default': 'true',
        'description': '是否启用移动端震动提醒',
        'category': 'notification'
    },
    'notification.mention_sound': {
        'name': '@提醒声音',
        'value_type': 'boolean',
        'default': 'true',
        'description': '@提及是否使用特殊提醒音',
        'category': 'notification'
    },
    'notification.badge_enabled': {
        'name': '角标显示',
        'value_type': 'boolean',
        'default': 'true',
        'description': '是否在浏览器标签显示未读数角标',
        'category': 'notification'
    },

    # ==================== 高级设置 ====================
    'advanced.cache_ttl_seconds': {
        'name': '缓存过期时间',
        'value_type': 'integer',
        'default': '300',
        'description': '系统缓存默认过期时间（秒）',
        'category': 'advanced',
        'validation': {'min': 60, 'max': 86400}
    },
    'advanced.api_rate_limit': {
        'name': 'API 限流',
        'value_type': 'integer',
        'default': '100',
        'description': '每用户每分钟最大请求次数',
        'category': 'advanced',
        'validation': {'min': 10, 'max': 1000}
    },
    'advanced.log_level': {
        'name': '日志级别',
        'value_type': 'string',
        'default': 'INFO',
        'description': '系统日志记录级别',
        'category': 'advanced',
        'choices': ['DEBUG', 'INFO', 'WARNING', 'ERROR']
    },
    'advanced.enable_compression': {
        'name': '响应压缩',
        'value_type': 'boolean',
        'default': 'true',
        'description': '是否启用响应数据压缩',
        'category': 'advanced'
    },
}

# 配置分类定义
CONFIG_CATEGORIES = [
    {'key': 'basic', 'name': '基础设置', 'icon': 'fas fa-cog', 'order': 1},
    {'key': 'chat', 'name': '聊天设置', 'icon': 'fas fa-comments', 'order': 2},
    {'key': 'file', 'name': '文件设置', 'icon': 'fas fa-file', 'order': 3},
    {'key': 'voice', 'name': '语音设置', 'icon': 'fas fa-microphone', 'order': 4},
    {'key': 'security', 'name': '安全设置', 'icon': 'fas fa-shield-alt', 'order': 5},
    {'key': 'notification', 'name': '通知设置', 'icon': 'fas fa-bell', 'order': 6},
    {'key': 'advanced', 'name': '高级设置', 'icon': 'fas fa-sliders-h', 'order': 7},
]


TURN_SECRET = config('TURN_SECRET')
TURN_REALM = config('TURN_REALM')