"""
Django settings for company_chat project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import sys
import os
from decouple import config
from datetime import timedelta
import re
import datetime

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-fz(25n_*5fk$glzg%mh_imzritgz4_syd5nls3x1u3-3o*j4y-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = config('ALLOWED_HOSTS', cast=lambda x: x.split(',')) or ['*']

# 必须在 INSTALLED_APPS 之前设置
AUTH_USER_MODEL = 'accounts.CustomUser'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',  # 必须保留，提供认证框架
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third party apps
    'rest_framework',
    'channels',
    'corsheaders',

    # Local apps - accounts 必须在 chat 之前
    'accounts',  # 自定义用户模型应用
    'chat',
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",  # 跨域中间件
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'accounts.middleware.ApiLoggingMiddleware',
    'chat.middleware.SystemConfigCacheMiddleware',  # 🔧 添加配置缓存中间件
]

ROOT_URLCONF = 'company_chat.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'company_chat.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

if sys.platform == 'linux':

    DATABASES = {
        # 'default': {
        #     'ENGINE': 'django.db.backends.sqlite3',
        #     'NAME': BASE_DIR / 'db.sqlite3',
        # }
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': config('DB_NAME'),
            'USER': config('DB_USER'),
            'PASSWORD': config('DB_PASSWORD'),
            'HOST': config('DB_HOST'),
            'PORT': config('DB_PORT'),
            # 'CONN_MAX_AGE': config('CONN_MAX_AGE', default=7200, cast=int),
            'CONN_MAX_AGE': 60,  # 连接最大存活时间（秒）
            'CONN_HEALTH_CHECKS': True,  # 连接健康检查
            'OPTIONS': {
                'connect_timeout': 15,
                'options': '-c statement_timeout=30000',
                'keepalives': 1,  # 启用 TCP Keepalive
                'keepalives_idle': 30,  # 空闲 30 秒后发送探测包
            },

        }
    }

    # redis 配置
    REDIS_HOST = config('REDIS_HOST')
    REDIS_PASSWORD = config('REDIS_PASSWORD')
    REDIS_PORT = config('REDIS_PORT', default=6379, cast=int)
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

    # redis 配置
    REDIS_HOST = '127.0.0.1'
    REDIS_PASSWORD = 'dayue123456'
    REDIS_PORT = 6379

# REDIS_LOCATION = f"redis://:{REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT}"
REDIS_LOCATION = f"redis://{REDIS_HOST}:{REDIS_PORT}"

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'chat.consumers': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'channels': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

# ASGI application
ASGI_APPLICATION = 'company_chat.asgi.application'

# # Channels Layer (Redis)
# CHANNEL_LAYERS = {
#     "default": {
#         "BACKEND": "channels_redis.core.RedisChannelLayer",
#         "CONFIG": {
#             "hosts": [(REDIS_HOST, REDIS_PORT)],
#             "capacity": 1500,  # 每个频道容量
#             "expiry": 60,  # 消息过期时间（秒）
#             "prefix": "asgi",  # Redis key 前缀
#
#         },
#     },
# }
#
# # 🔧 关键修复：缓存配置
# CACHES = {
#     "default": {
#         "BACKEND": "django.core.cache.backends.redis.RedisCache",
#         "LOCATION": REDIS_LOCATION,
#         "OPTIONS": {
#             "MAX_ENTRIES": 1000,
#             "CULL_FREQUENCY": 3,
#         }
#     }
# }


# # 🔧 关键修复：缓存配置
# CACHES = {
#     "default": {
#         "BACKEND": "django.core.cache.backends.redis.RedisCache",
#         "LOCATION": f"redis://{REDIS_HOST}:{REDIS_PORT}/1",  # 数据库 1
#         "OPTIONS": {
#             "CONNECTION_POOL_KWARGS": {
#                 "max_connections": 50,
#                 "retry_on_timeout": True,
#                 "socket_connect_timeout": 5,
#                 "socket_timeout": 5,
#                 "health_check_interval": 30,
#             },
#             "SERIALIZER": "django.core.cache.backends.redis.serializers.JSONSerializer",
#         },
#         "KEY_PREFIX": "company_chat",
#         "TIMEOUT": 300,
#     }
# }

# 安装 django-redis
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",  # ✅ 使用 django-redis
        "LOCATION": f"redis://{REDIS_HOST}:{REDIS_PORT}/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            # ✅ 连接池配置（django-redis 支持 CONNECTION_POOL_KWARGS）
            "CONNECTION_POOL_KWARGS": {
                "max_connections": 50,
                "retry_on_timeout": True,
                "socket_connect_timeout": 5,
                "socket_timeout": 5,
                "health_check_interval": 30,
            },
            # ✅ 序列化
            "SERIALIZER": "django_redis.serializers.json.JSONSerializer",
        },
        "KEY_PREFIX": "company_chat",
        "TIMEOUT": 300,
    }
}


# 🔧 确保 Channels 使用独立的 Redis 数据库（避免缓存键冲突）
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            # ✅ 使用数据库 2，与 CACHES 的数据库 1 分离
            "hosts": [f"redis://{REDIS_HOST}:{REDIS_PORT}/2"],
            "capacity": 1500,
            "expiry": 60,
            "prefix": "asgi",
            # "pool_size": 20,  # ✅ 连接池大小, 报错
        },
    },
}


# WebSocket 超时配置
WEBSOCKET_CONNECT_TIMEOUT = 30  # 连接超时（秒）
WEBSOCKET_DISCONNECT_TIMEOUT = 10  # 断开超时（秒）

# REST Framework配置
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    # ❌ 错误：全局要求认证
    # 'DEFAULT_PERMISSION_CLASSES': (
    #     'rest_framework.permissions.IsAuthenticated',
    # ),

    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
}

# JWT 配置
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=8),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}

# CORS配置
CORS_ALLOW_ALL_ORIGINS = True  # 生产环境应限制为具体域名

# 认证后端
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# ================================================= #
# ******************* 跨域的配置 ******************* #
# ================================================= #

# 允许所有来源（仅用于开发环境）
# CORS_ALLOW_ALL_ORIGINS = True

# 或者指定允许的前端地址（推荐用于生产环境）
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",  # 前端地址
    "http://192.168.20.33:5173",  # 前端地址
    "http://chat.first-iq.com:10900",  # 前端地址
    "http://chat.first-iq.com:10901",  # 前端地址
    "https://chat.first-iq.com",  # 前端地址
]

# 指定允许的后端地址（推荐用于生产环境）
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",  # 前端地址
    "http://192.168.20.33:5173",  # 前端地址
    "http://chat.first-iq.com:10900",
    "http://chat.first-iq.com:10901",  # 前端地址
    "https://chat.first-iq.com",  # 前端地址
    # Add other trusted origins if needed
]

# 暴露自定义头,否则前端无法获取自定义头
CORS_EXPOSE_HEADERS = ['Captcha-Key', 'Content-Disposition']

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

# LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC'

# Internationalization
LANGUAGE_CODE = 'zh-hans'
TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

# STATIC_URL = '/static/'
# STATICFILES_DIRS = [BASE_DIR / 'static']
# STATIC_ROOT = BASE_DIR / 'staticfiles'
#
# MEDIA_URL = '/media/'
# MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'

if sys.platform == 'linux':

    STATIC_URL = 'static/'
    STATIC_ROOT = BASE_DIR / 'static'

    # 素材上传配置
    MEDIA_URL = 'media/'
    MEDIA_ROOT = BASE_DIR / 'media'
else:
    # 静态文件配置
    STATIC_URL = '/static/'
    STATICFILES_DIRS = [
        os.path.join(BASE_DIR, 'static'),  # 前端静态资源目录
    ]
    STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # collectstatic 收集目录

    # 多媒体文件配置（用户上传的文件）
    MEDIA_URL = '/media/'
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')  # 上传文件存储目录

    # 确保 media 目录存在
    if not os.path.exists(MEDIA_ROOT):
        os.makedirs(MEDIA_ROOT)

BASE_URL = 'https://chat.first-iq.com/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 静态文件版本（每次部署更新）
STATIC_VERSION = '20260310-a9487be'

# 构建时间
BUILD_TIME = str(datetime.datetime.now())[:19]

# # 静态文件存储（生产环境使用 WhiteNoise 或 CDN）
# STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# # WhiteNoise 配置
# WHITENOISE_MAX_AGE = 31536000  # 1年
# WHITENOISE_IMMUTABLE_FILE_TEST = lambda path, url: re.match(r'^.+\.[0-9a-f]{12}\..+$', url)


API_LOG_ENABLE = True
# API_LOG_METHODS = 'ALL' # ['POST', 'DELETE']
API_LOG_METHODS = ["POST", "UPDATE", "DELETE", "PUT", 'PATCH']  # ['POST', 'DELETE']
API_MODEL_MAP = {
    "/api/auth/profile/": "个人资料",
    "/api/auth/login/": "登录",
    "/api/auth/logout/": "登出",
    "/api/chat/upload/": "文件管理",
    "/api/chat/rooms/": "聊天室管理",
    "/api/chat/messages/": "消息管理",
    "/api/auth/admin/users/": "用户管理",
}
EXLUDE_API_LOG = [
    "/api/chat/messages/mark_as_read/"  # 标记已读
]
API_METHOD_MAP = {
    'GET': '查询',
    'POST': '新建',
    'PUT': '更新',
    'DELETE': '删除',
    'PATCH': '修改',
}



# ================================================= #
# ******************* 邮箱配置 ******************* #
# ================================================= #
# smtp后端,默认配置
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# 控制台后端开发时使用
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

EMAIL_HOST = config('EMAIL_HOST')
EMAIL_PORT = config('EMAIL_PORT', default=465, cast=int)
EMAIL_HOST_USER = DEFAULT_FROM_EMAIL = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
EMAIL_USE_SSL = config('EMAIL_USE_SSL', default=True, cast=bool)
# EMAIL_FROM_EMAIL = config('EMAIL_FROM_EMAIL')
EMAIL_SUBJECT_PREFIX = config('EMAIL_SUBJECT_PREFIX')
EMAIL_TIMEOUT = config('EMAIL_TIMEOUT', default=300, cast=int)  # 超时(5分钟)
