"""
Django settings for company_chat project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import sys
import os
from decouple import config
from datetime import timedelta
import re
import datetime

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-fz(25n_*5fk$glzg%mh_imzritgz4_syd5nls3x1u3-3o*j4y-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = config('ALLOWED_HOSTS', cast=lambda x: x.split(',')) or ['*']

# 必须在 INSTALLED_APPS 之前设置
AUTH_USER_MODEL = 'accounts.CustomUser'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',  # 必须保留，提供认证框架
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'django_celery_beat',

    # Third party apps
    'rest_framework',
    'channels',
    'corsheaders',

    # Local apps - accounts 必须在 chat 之前
    'accounts',  # 自定义用户模型应用
    'chat',
    'cloud',
    'tasks',
    'oa',  # OA办公（考勤打卡+审批）
    'org',  # 组织架构（多企业隔离）

    # JWT token 黑名单管理（需执行 migrate 创建表）
    'rest_framework_simplejwt.token_blacklist',
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",  # 跨域中间件
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # 👈 补充这行
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'accounts.middleware.TenantMiddleware',  # 多租户中间件
    # 'cloud.middleware.OnlyOfficeMiddleware',  # 🔧 添加这行
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'accounts.middleware.ApiLoggingMiddleware',
    # 'chat.middleware.SystemConfigCacheMiddleware',  # 🔧 添加配置缓存中间件
]

INSTALLED_APPS += ['debug_toolbar']
MIDDLEWARE.insert(0, 'debug_toolbar.middleware.DebugToolbarMiddleware')

ROOT_URLCONF = 'company_chat.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'company_chat.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

if sys.platform == 'linux':

    DATABASES = {
        # 'default': {
        #     'ENGINE': 'django.db.backends.sqlite3',
        #     'NAME': BASE_DIR / 'db.sqlite3',
        # }
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': config('DB_NAME'),
            'USER': config('DB_USER'),
            'PASSWORD': config('DB_PASSWORD'),
            'HOST': config('DB_HOST'),
            'PORT': config('DB_PORT'),
            'CONN_MAX_AGE': config('CONN_MAX_AGE', default=0, cast=int),
            # 'CONN_MAX_AGE': 60,  # 把 CONN_MAX_AGE 从 60 调小（0 或 30），减少每条连接在 Django 侧挂 60 秒的常驻占用。
            'CONN_HEALTH_CHECKS': True,  # 连接健康检查
            'OPTIONS': {
                'connect_timeout': 10,
                'options': '-c statement_timeout=30000',
                'keepalives': 1,  # 启用 TCP Keepalive
                'keepalives_idle': 30,  # 空闲 30 秒后发送探测包
                # ❌ 删除 pool_size 和 max_overflow（psycopg2 不支持）
                # 'pool_size': 10,
                # 'max_overflow': 20,
            },

        }
    }

    # redis 配置
    REDIS_HOST = config('REDIS_HOST')
    REDIS_PASSWORD = config('REDIS_PASSWORD')
    REDIS_PORT = config('REDIS_PORT', default=6379, cast=int)

    # 生产/Linux 环境：尝试使用 WhiteNoise，失败则自动降级
    # try:
    #     import whitenoise
    #
    #     STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
    # except ImportError:
    #     STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.ManifestStaticFilesStorage'

else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

    # redis 配置
    REDIS_HOST = '127.0.0.1'
    REDIS_PASSWORD = 'dayue123456'
    REDIS_PORT = 6379

    # 开发/Windows/macOS 环境：使用默认存储
    STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'

# REDIS_LOCATION = f"redis://:{REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT}"
REDIS_LOCATION = f"redis://{REDIS_HOST}:{REDIS_PORT}"

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'chat.consumers': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'channels': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

# ASGI application
ASGI_APPLICATION = 'company_chat.asgi.application'

# 安装 django-redis
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",  # ✅ 使用 django-redis
        "LOCATION": f"redis://{REDIS_HOST}:{REDIS_PORT}/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            # ✅ 连接池配置（django-redis 支持 CONNECTION_POOL_KWARGS）
            "CONNECTION_POOL_KWARGS": {
                "max_connections": 100,
                "retry_on_timeout": True,
                "socket_connect_timeout": 5,
                "socket_timeout": 5,
                "health_check_interval": 30,
            },
            # ✅ 序列化
            "SERIALIZER": "django_redis.serializers.json.JSONSerializer",
        },
        "KEY_PREFIX": "company_chat",
        "TIMEOUT": 300,
    }
}

# 🔧 确保 Channels 使用独立的 Redis 数据库（避免缓存键冲突）
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            # ✅ 使用数据库 2，与 CACHES 的数据库 1 分离
            "hosts": [f"redis://{REDIS_HOST}:{REDIS_PORT}/2"],
            "capacity": 1500,  # 默认 100
            "expiry": 10,  # 默认 60 秒
            "prefix": "asgi",
            # "close_timeout": 10,  # 增加到 10 秒
            # "pool_size": 20,  # ✅ 连接池大小, 报错
        },
    },
}

celery_redis_host = config('CELERY_REDIS_HOST')
celery_redis_port = config('CELERY_REDIS_PORT')
celery_redis_password = config('CELERY_REDIS_PASSWORD')
ENABLE_LOGIN_ANALYSIS_LOG = True
# CELERY_REDIS_LOCATION = f"redis://:{celery_redis_password}@{celery_redis_host}:{celery_redis_port}/3"
CELERY_REDIS_LOCATION = f"redis://{celery_redis_host}:{celery_redis_port}/3"

# Celery 配置
CELERY_BROKER_URL = f'{CELERY_REDIS_LOCATION}'
CELERY_RESULT_BACKEND = f'{CELERY_REDIS_LOCATION}'
CELERY_TIMEZONE = "Asia/Shanghai"
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# 添加这些关键配置
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_ENABLE_UTC = False

AES_KEY = config('AES_KEY')
SM4_KEY = config('SM4_KEY')

KEEP_DAYS = config('KEEP_DAYS', default=15, cast=int)

# WebSocket 超时配置
WEBSOCKET_CONNECT_TIMEOUT = 30  # 连接超时（秒）
WEBSOCKET_DISCONNECT_TIMEOUT = 10  # 断开超时（秒）

# REST Framework配置
REST_FRAMEWORK = {
    'DEFAULT_FILTER_BACKENDS': [
        'org.filters.TenantFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    # ❌ 错误：全局要求认证
    # 'DEFAULT_PERMISSION_CLASSES': (
    #     'rest_framework.permissions.IsAuthenticated',
    # ),

    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
}

# JWT 配置
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=config('ACCESS_TOKEN_EXPIRES_HOURS', default=8, cast=int)),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=config('REFRESH_TOKEN_EXPIRES_DAYS', default=7, cast=int)),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}

# CORS配置
CORS_ALLOW_ALL_ORIGINS = True  # 生产环境应限制为具体域名

# 认证后端
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# ================================================= #
# ******************* 跨域的配置 ******************* #
# ================================================= #

# 允许所有来源（仅用于开发环境）
# CORS_ALLOW_ALL_ORIGINS = True

# 或者指定允许的前端地址（推荐用于生产环境）
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",  # 前端地址
    "http://192.168.20.33:5173",  # 前端地址
    "http://chat.first-iq.com:10900",  # 前端地址
    "http://chat.first-iq.com:10901",  # 前端地址
    "https://chat.first-iq.com",  # 前端地址
    "http://onlyoffice.first-iq.com",  # OnlyOffice 域名
    "http://onlyoffice.first-iq.com:12280",  # OnlyOffice 域名
    "http://192.168.1.122",  # OnlyOffice 可选，直接 IP 访问
    "http://192.168.1.122:8000",  # OnlyOffice
    "http://192.168.1.130",  # Django
    "http://192.168.1.130:10900",  # Django
]

# 指定允许的后端地址（推荐用于生产环境）
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",  # 前端地址
    "http://192.168.20.33:5173",  # 前端地址
    "http://chat.first-iq.com:10900",
    "http://chat.first-iq.com:10901",  # 前端地址
    "https://chat.first-iq.com",  # 前端地址
    "http://onlyoffice.first-iq.com",  # OnlyOffice 域名
    "http://onlyoffice.first-iq.com:12280",  # OnlyOffice 域名
    # Add other trusted origins if needed
]

# 暴露自定义头,否则前端无法获取自定义头
CORS_EXPOSE_HEADERS = ['Captcha-Key', 'Content-Disposition']

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

# LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC'

# Internationalization
LANGUAGE_CODE = 'zh-hans'
TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

# STATIC_URL = '/static/'
# STATICFILES_DIRS = [BASE_DIR / 'static']
# STATIC_ROOT = BASE_DIR / 'staticfiles'
#
# MEDIA_URL = '/media/'
# MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'

if sys.platform == 'linux':

    STATIC_URL = 'static/'
    STATIC_ROOT = BASE_DIR / 'static'

    # 素材上传配置
    MEDIA_URL = 'media/'
    MEDIA_ROOT = BASE_DIR / 'media'
else:
    # 静态文件配置
    STATIC_URL = '/static/'
    STATICFILES_DIRS = [
        os.path.join(BASE_DIR, 'static'),  # 前端静态资源目录
    ]
    STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # collectstatic 收集目录

    # 多媒体文件配置（用户上传的文件）
    MEDIA_URL = '/media/'
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')  # 上传文件存储目录

    # 确保 media 目录存在
    if not os.path.exists(MEDIA_ROOT):
        os.makedirs(MEDIA_ROOT)

BASE_URL = 'https://chat.first-iq.com/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 静态文件版本（每次部署更新）
STATIC_VERSION = '20260901-b9b07be'

# 构建时间
BUILD_TIME = str(datetime.datetime.now())[:19]

# # 静态文件存储（生产环境使用 WhiteNoise 或 CDN）
# STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# # WhiteNoise 配置
# WHITENOISE_MAX_AGE = 31536000  # 1年
# WHITENOISE_IMMUTABLE_FILE_TEST = lambda path, url: re.match(r'^.+\.[0-9a-f]{12}\..+$', url)


API_LOG_ENABLE = True
# API_LOG_METHODS = 'ALL' # ['POST', 'DELETE']
API_LOG_METHODS = ["POST", "UPDATE", "DELETE", "PUT", 'PATCH']  # ['POST', 'DELETE']
# 接口模型映射
API_MODEL_MAP = {
    # ====== 认证模块 ======
    "/api/auth/login/": "登录",
    "/api/auth/logout/": "登出",
    "/api/auth/register/": "用户注册",
    "/api/auth/profile/": "个人资料",
    "/api/auth/change-password/": "修改密码",
    "/api/auth/upload-avatar/": "上传头像",
    "/api/auth/me/": "用户信息",
    "/api/auth/list/": "用户列表",
    "/api/auth/friends/": "好友管理",
    "/api/auth/search_users/": "搜索用户",
    "/api/auth/search_assignees/": "搜索任务执行人",
    "/api/auth/online/": "在线用户",
    "/api/auth/request_password_reset/": "密码重置请求",
    "/api/auth/confirm_password_reset/": "密码重置确认",
    "/api/auth/token/refresh/": "Token刷新",
    "/api/auth/token/verify/": "Token验证",
    "/api/auth/contact/submit/": "咨询提交",

    # ====== 管理控制台 ======
    "/api/auth/admin/users/": "用户管理",
    "/api/auth/admin/dashboard/": "数据统计",
    "/api/auth/admin/login-logs/": "登录日志",
    "/api/auth/admin/operation-logs/": "操作日志",

    # ====== 聊天模块 ======
    "/api/chat/rooms/": "聊天室管理",
    "/api/chat/rooms/<int:pk>/soft_delete/": "软删除聊天",
    "/api/chat/rooms/<int:pk>/dismiss_chat/": "解散群聊",
    "/api/chat/rooms/<int:pk>/update_group/": "更新群聊",
    "/api/chat/rooms/<int:pk>/add_member/": "添加群成员",
    "/api/chat/rooms/<int:pk>/remove_member/": "移除群成员",
    "/api/chat/rooms/<int:pk>/pin_chat/": "置顶聊天",
    "/api/chat/rooms/<int:pk>/mute_chat/": "消息免打扰",
    "/api/chat/rooms/search_chats/": "搜索聊天",
    "/api/chat/messages/": "消息管理",
    "/api/chat/messages/<int:pk>/soft_delete/": "删除消息",
    "/api/chat/messages/<int:pk>/revoke/": "撤销消息",
    "/api/chat/messages/clear_history/": "清空历史消息",
    "/api/chat/messages/unread_count/": "未读消息数",
    "/api/chat/upload/": "文件上传",
    "/api/chat/audio/<int:file_id>/format/": "音频格式",
    "/api/chat/version/": "版本信息",
    "/api/chat/admin/chat-rooms/": "聊天室管理",
    "/api/chat/admin/statistics/": "聊天统计",
    "/api/chat/admin/settings/": "系统设置",
    "/api/chat/system/configs/": "系统配置",
    "/api/chat/turn/credentials/": "TURN凭证",

    # ====== 企业网盘 ======
    # 文件上传（分片/秒传）相关，必须放在 /api/cloud/files/ 之前以优先匹配
    "/api/cloud/files/init_upload/": "初始化文件上传",
    "/api/cloud/files/upload_chunk/": "上传文件分片",
    "/api/cloud/files/merge_chunks/": "合并分片完成上传",
    "/api/cloud/files/check_session/": "检查上传会话",
    "/api/cloud/files/cancel_upload/": "取消上传",
    "/api/cloud/files/save_from_url/": "从URL保存文件到网盘",
    "/api/cloud/files/save_from_chat/": "从聊天保存文件到网盘",
    "/api/cloud/files/": "文件管理",
    "/api/cloud/cloudfiles/": "文件下载",
    "/api/cloud/folders/": "文件夹管理",
    "/api/cloud/search-users/": "搜索用户",
    "/api/cloud/shares/": "文件分享",
    "/api/cloud/comments/": "文件评论",
    "/api/cloud/dashboard/": "网盘统计",
    "/api/cloud/documents/": "文档编辑",
    # ====== 企业网盘-系统配置（具体路径在前，通用 /api/cloud/settings/ 放最后，保证前缀匹配优先命中具体标签）======
    "/api/cloud/settings/categories/": "网盘配置分类",
    "/api/cloud/settings/list_configs/": "网盘配置列表",
    "/api/cloud/settings/update_config/": "网盘配置更新",
    "/api/cloud/settings/reset_to_default/": "网盘配置重置",
    "/api/cloud/settings/clear_cache/": "网盘清除缓存",
    "/api/cloud/settings/system_info/": "网盘系统信息",
    "/api/cloud/settings/export_configs/": "网盘配置导出",
    "/api/cloud/settings/onlyoffice_configs/": "OnlyOffice协同配置",
    "/api/cloud/settings/update_onlyoffice_configs/": "OnlyOffice协同配置保存",
    "/api/cloud/settings/user-permissions/": "协同编辑用户权限",
    "/api/cloud/settings/user-permissions/<int:user_id>/": "协同编辑用户权限详情",
    "/api/cloud/settings/users-for-permission/": "协同编辑权限用户搜索",
    "/api/cloud/settings/operation-permissions/": "网盘操作权限配置",
    "/api/cloud/settings/user-operation-permissions/": "网盘用户操作权限",
    "/api/cloud/settings/user-operation-permissions/<int:user_id>/": "网盘用户操作权限详情",
    "/api/cloud/settings/users-for-operation-permission/": "网盘操作权限用户搜索",
    "/api/cloud/settings/effective-permission/": "网盘操作权限生效值",
    "/api/cloud/settings/": "网盘设置",
    # 共享文件夹（含成员管理）
    "/api/cloud/shared-folders/": "共享文件夹",
    "/api/cloud/shared-folders/<uuid:folder_id>/add_member/": "共享文件夹添加成员",
    "/api/cloud/shared-folders/<uuid:folder_id>/update_member/": "共享文件夹更新成员",
    "/api/cloud/shared-folders/<uuid:folder_id>/remove_member/": "共享文件夹移除成员",
    "/api/cloud/shared-folders/<uuid:folder_id>/members/": "共享文件夹成员列表",
    "/api/cloud/shared-folders/<uuid:folder_id>/my_permission/": "共享文件夹我的权限",
    "/api/cloud/shared-folders/<uuid:folder_id>/move_items/": "共享文件夹移动文件",
    "/api/cloud/operation-logs/": "操作日志",
    "/s/<str:share_code>/": "分享访问",
    "/s/<str:share_code>/download/": "分享下载",

    # ====== 任务中心 ======
    "/api/tasks/": "任务中心",

    # ====== OA办公 ======
    "/api/oa/attendance/": "考勤打卡",
    "/api/oa/attendance/statistics/": "考勤统计",
    "/api/oa/attendance/today/": "今日打卡",
    "/api/oa/attendance/clock-in/": "上班打卡",
    "/api/oa/attendance/clock-out/": "下班打卡",
    "/api/oa/attendance/makeup/": "考勤补卡",
    "/api/oa/attendance/export/": "考勤导出",
    "/api/oa/attendance/<int:pk>/convert-coords/": "坐标转换",
    "/api/oa/attendance/attendance-configs/": "考勤配置列表",
    "/api/oa/attendance/save-attendance-config/": "保存考勤配置",
    "/api/oa/attendance/delete-attendance-config/<int:pk>/": "删除考勤配置",
    "/api/oa/attendance/my-config/": "我的考勤配置",
    "/api/oa/attendance/members/": "考勤成员列表",
    "/api/oa/attendance/user-attendance-configs/": "个人考勤配置列表",
    "/api/oa/attendance/save-user-attendance-config/": "保存个人考勤配置",
    "/api/oa/attendance/delete-user-attendance-config/<int:pk>/": "删除个人考勤配置",
    "/api/oa/attendance/calendar-stats/": "考勤日历统计",
    "/api/oa/attendance/calendar_stats/": "考勤日历统计",
    "/api/oa/attendance/calendar-day-detail/": "考勤日历日期详情",
    "/api/oa/approval/": "OA审批",
    "/api/oa/approval/types/": "审批类型管理",
    "/api/oa/approval/approval_chain/": "审批链预览",
    "/api/oa/approval/geocode/": "地理编码",
    "/api/oa/approval/admins/": "审批管理员",
    "/api/oa/approval/departments/": "审批部门",
    "/api/oa/approval/all-departments/": "全部部门",
    "/api/oa/approval/org_departments/": "组织部门",
    "/api/oa/approval/upload-attachment/": "审批附件上传",
    "/api/oa/approval/dept-configs/": "审批配置列表",
    "/api/oa/approval/save-dept-config/": "保存审批配置",
    "/api/oa/approval/delete-dept-config/<int:pk>/": "删除审批配置",
    "/api/oa/approval/search-cc-users/": "搜索抄送人",
    "/api/oa/approval/search-cc-departments/": "搜索抄送部门",
    "/api/oa/approval/my-pending/": "我的待审批",
    "/api/oa/approval/draft/": "审批草稿",
    "/api/oa/approval/drafts/": "审批草稿列表",
    "/api/oa/approval/<int:pk>/": "审批详情",
    "/api/oa/approval/<int:pk>/approve/": "审批通过",
    "/api/oa/approval/<int:pk>/reject/": "审批驳回",
    "/api/oa/approval/<int:pk>/deferred/": "暂缓审批",
    "/api/oa/approval/<int:pk>/processing/": "办理中审批",
    "/api/oa/approval/<int:pk>/cancel/": "审批撤销",
    "/api/oa/approval/<int:pk>/re-edit/": "审批重新编辑",
    "/api/oa/approval/<int:pk>/delete-draft/": "删除审批草稿",
    "/api/oa/approval/<int:pk>/update-draft/": "更新审批草稿",
    "/api/oa/approval/<int:pk>/send-private/": "审批私聊提醒",
    "/api/oa/approval/<int:pk>/upload-receipt/": "审批票据回传",
    "/api/oa/approval/<int:pk>/delete-receipt/": "删除回传票据",
    "/api/oa/approval/custom-payment-methods/": "自定义收款方式库",
    "/api/oa/approval/custom-payment-method/<int:pk>/": "删除自定义收款方式",
    "/api/oa/approval/finance-specialists/": "财务专员管理",
    "/api/oa/approval/finance-specialists/<int:pk>/": "财务专员管理详情",
    "/api/oa/approval/finance-specialist-users/": "财务专员用户搜索",
    "/api/oa/announcements/": "集团公告",
    "/api/oa/announcements/<int:pk>/": "集团公告详情",
    "/api/oa/announcements/<int:pk>/publish/": "集团公告发布",
    "/api/oa/announcements/<int:pk>/comments/": "集团公告评论列表",
    "/api/oa/announcements/<int:pk>/add-comment/": "集团公告添加评论",
    "/api/oa/material/items/": "物资物品库",
    "/api/oa/material/item-search/": "物资物品联想",
    "/api/oa/material/items/<int:pk>/": "物资物品编辑/删除",
    "/api/oa/material/requirement-search/": "可领用需求单搜索",
    "/api/oa/material/requirement-detail/": "需求单详情(自动带出)",
    "/api/oa/material/stock-in/": "物资入库确认",
    "/api/oa/material/requirements/": "物资需求单列表",
    "/api/oa/material/requisitions/": "物资领用单列表",
    "/api/oa/material/requirement-status/": "物资需求单状态流转",
    "/api/oa/subsidy/upload-invoice/": "补贴发票上传",
    "/api/oa/subsidy/ocr-invoice/": "补贴票据OCR识别",
    "/api/oa/subsidy/qr-scan/": "补贴票据二维码扫描",
    "/api/oa/subsidy/ocr-status/": "补贴票据OCR识别状态",
    "/api/oa/subsidy/invoice-preview/": "补贴票据预览",
    "/api/oa/subsidy/upload-voucher/": "补贴支付凭证上传",
    "/api/oa/subsidy/upload-proof/": "补贴支付截图上传",
    "/api/oa/subsidy/payment-info/": "用户收款账号信息",
    "/api/oa/subsidy/account/": "补贴账户",
    "/api/oa/subsidy/wallet/": "补贴钱包",
    "/api/oa/subsidy/withdraw/": "补贴提现",
    "/api/oa/subsidy/withdrawals/": "我的提现记录",
    "/api/oa/subsidy/withdrawals/all/": "提现支付列表",
    "/api/oa/subsidy/withdrawals/export/": "提现申请导出",
    "/api/oa/subsidy/withdrawals/<int:pk>/pay/": "提现支付",
    "/api/oa/subsidy/withdrawals/<int:pk>/reject/": "提现驳回",
    "/api/oa/subsidy/payments/": "补贴发放记录",
    "/api/oa/subsidy/all/": "补贴申领核验列表",
    "/api/oa/subsidy/export/": "补贴申领核验导出",
    "/api/oa/subsidy/configs/": "补贴配置列表",
    "/api/oa/subsidy/save-config/": "补贴配置保存",
    "/api/oa/subsidy/clear-ocr-cache/": "清除发票识别缓存",
    "/api/oa/subsidy/delete-config/<int:pk>/": "补贴配置删除",
    "/api/oa/subsidy/<int:pk>/re-submit/": "补贴申领重新提交",
    "/api/oa/subsidy/<int:pk>/delete-my/": "补贴申领删除",
    "/api/oa/subsidy/<int:pk>/verify/": "补贴申领核验",
    "/api/oa/subsidy/<int:pk>/verify-invoice/": "补贴发票验真",
    "/api/oa/subsidy/<int:pk>/invoice-verify-status/": "补贴发票验真状态",
    "/api/oa/subsidy/<int:pk>/update-invoice-type/": "补贴发票类型修改",
    "/api/oa/subsidy/": "员工普惠补贴",
    "/api/oa/work-calendar/": "工作日历",
    "/api/oa/work-calendar/day/": "工作日历-当日详情",
    "/api/oa/work-calendar/stats/": "工作日历-时间线统计",
    "/api/oa/work-calendar/approval-efficiency/": "工作日历-审批效率",
    "/api/oa/work-calendar/approval-leaderboard/": "工作日历-审批效率排行榜",
    "/api/oa/work-calendar/digest-config/": "每日通知配置",
    "/api/oa/work-calendar/digest-send/": "每日通知手动发送",
    "/api/oa/work-calendar/work-summary-stats/": "每日总结完成情况统计",
    "/api/oa/work-calendar/org-activity/": "成员关系与活跃度可视化",
    "/api/oa/work-calendar/member-search/": "成员关系-成员搜索",
    "/api/oa/work-summary/": "每日工作总结",
    "/api/oa/work-summary/upload/": "每日总结文件上传",
    "/api/oa/work-summary/all/": "每日总结团队列表",
    "/api/oa/work-summary/config/": "每日总结模型配置",
    "/api/oa/work-summary/members/": "每日总结成员列表",
    "/api/oa/work-summary/range/": "每日总结范围分析",
    "/api/oa/work-summary/range/<int:pk>/": "每日总结范围分析详情",
    "/api/oa/work-summary/<int:pk>/": "每日总结详情",
    "/api/oa/work-summary/<int:pk>/analyze/": "每日总结重新分析",
    "/api/oa/work-summary/<int:pk>/share/": "每日总结分享私聊",
    "/api/oa/work-summary/<int:pk>/export-pdf/": "每日总结导出PDF",
    "/api/system/watermark-config/": "企业水印配置",
    "/api/system/print-log/": "打印记录",
    "/api/oa/notifications/": "工作通知",
    "/api/oa/notifications/unread-count/": "通知未读数",
    "/api/oa/notifications/mark-all-read/": "通知全部已读",
    "/api/oa/notifications/<int:pk>/mark-read/": "标记通知已读",

    # ====== 组织架构 ======
    "/api/org/tenants/": "企业管理",
    "/api/org/tenants/<int:pk>/switch/": "切换企业",
    "/api/org/tenants/<int:pk>/members/": "企业成员",
    "/api/org/tenants/<int:pk>/invite/": "邀请成员",
    "/api/org/tenants/<int:pk>/remove_member/": "移出企业",
    "/api/org/tenants/<int:pk>/update_member/": "更新成员信息",
    "/api/org/tenants/<int:pk>/member_role/": "成员角色",
    "/api/org/tenants/<int:pk>/stats/": "企业统计",
    "/api/org/tenants/search_users/": "搜索用户",
    "/api/org/tenants/search_tenant_members/": "搜索企业成员",
    "/api/org/tenants/search_all_users/": "搜索全部用户",
    "/api/org/departments/": "部门管理",
    "/api/org/departments/<int:pk>/move/": "移动部门",
    "/api/org/departments/<int:pk>/sort/": "部门排序",
    "/api/org/departments/<int:pk>/set_leaders/": "设置负责人",
    "/api/org/departments/<int:pk>/set_deputies/": "设置副负责人",
    "/api/org/departments/<int:pk>/members/": "部门成员",
    "/api/org/departments/<int:pk>/add_members/": "添加部门成员",
    "/api/org/departments/<int:pk>/remove_members/": "移除部门成员",
    "/api/org/departments/<int:pk>/update_member_position/": "更新成员职位",
    "/api/org/departments/<int:pk>/sync_all_members/": "同步全部成员",
    "/api/org/departments/<int:pk>/leaders/": "部门负责人",
    "/api/org/departments/<int:pk>/convert_to_tenant/": "部门转子公司",
    "/api/org/departments/<int:pk>/revert_to_department/": "子公司恢复为部门",
    "/api/org/departments/create_sub_tenant/": "集团创建子公司",
    "/api/org/departments/rebuild_report_relations/": "重建汇报关系",
    "/api/org/departments/<int:pk>/path/": "部门路径",
    "/api/org/departments/<int:pk>/org_chart/": "部门架构图",
    "/api/org/departments/search/": "搜索部门",
    "/api/org/org-chart/": "组织架构图",
    "/api/org/users/<int:pk>/departments/": "用户部门",
    "/api/org/users/<int:pk>/subordinates/": "下属列表",
    "/api/org/users/<int:pk>/set-supervisor/": "设置上级",
    "/api/org/users/<int:pk>/supervisors/": "上级列表",
    "/api/org/change-logs/": "组织变更日志",
}
EXLUDE_API_LOG = [
    "/api/chat/messages/mark_as_read/",  # 标记已读
    "/api/cloud/files/upload_chunk/",  # 文件分片上传
    "/api/oa/subsidy/export/",  # 普惠补贴导出（二进制文件）
]
API_METHOD_MAP = {
    'GET': '查询',
    'POST': '新建',
    'PUT': '更新',
    'OPTIONS': '查询',
    'HEAD': '查询',
    'UPDATE': '修改',
    'DELETE': '删除',
    'PATCH': '修改',
}

# ================================================= #
# ******************* 邮箱配置 ******************* #
# ================================================= #
# smtp后端,默认配置
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# 控制台后端开发时使用
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

EMAIL_HOST = config('EMAIL_HOST')
EMAIL_PORT = config('EMAIL_PORT', default=465, cast=int)
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
DEFAULT_FROM_EMAIL = config('EMAIL_FROM_EMAIL')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
EMAIL_USE_SSL = config('EMAIL_USE_SSL', default=True, cast=bool)
# EMAIL_FROM_EMAIL = config('EMAIL_FROM_EMAIL')
EMAIL_SUBJECT_PREFIX = config('EMAIL_SUBJECT_PREFIX')
EMAIL_TIMEOUT = config('EMAIL_TIMEOUT', default=300, cast=int)  # 超时(5分钟)

PASSWORD_RESET_TOKEN_EXPIRES_MINUTES = config('PASSWORD_RESET_TOKEN_EXPIRES_MINUTES', default=20, cast=int)
PASSWORD_RESET_TOKEN_EXPIRES_HOURS = config('PASSWORD_RESET_TOKEN_EXPIRES_HOURS', default=1, cast=int)

CONTACT_NOTIFICATION_EMAILS = config('CONTACT_NOTIFICATION_EMAILS', cast=lambda x: x.split(',')) or []

SYSTEM_NAME = '义乌吉通集团'

# 前端地址（用于生成重置链接）
FRONTEND_URL = config('FRONTEND_URL', default='https://chat.first-iq.com', cast=str)

# LOGGING = {
#     'version': 1,
#     'disable_existing_loggers': False,
#     'handlers': {
#         'console': {
#             'class': 'logging.StreamHandler',
#         },
#         'file': {
#             'class': 'logging.FileHandler',
#             'filename': '/www/yue/company_chat/logs/onlyoffice.log',
#         },
#     },
#     'loggers': {
#         'cloud.views': {
#             'handlers': ['console', 'file'],
#             'level': 'DEBUG',
#             'propagate': False,
#         },
#     },
# }


# # 🔧 OnlyOffice 配置
# ONLYOFFICE_URL = 'http://localhost:8080'  # OnlyOffice Document Server 地址
# ONLYOFFICE_SECRET = 'your-secret-key'  # JWT 密钥
# ONLYOFFICE_SERVER_URL = 'https://chat.first-iq.com/cloud/'  # 企业网盘地址
#
# # 文档版本保留策略
# DOCUMENT_VERSION_KEEP_COUNT = 10  # 保留最近 10 个版本
# DOCUMENT_VERSION_KEEP_DAYS = 30  # 保留 30 天
#
# # 编辑锁过期时间（分钟）
# DOCUMENT_EDIT_LOCK_EXPIRE_MINUTES = 30

# 🔧 OnlyOffice 配置
ONLYOFFICE = {
    # 🔧 Document Server 地址（服务器 2）
    # 'DOCUMENT_SERVER_URL': 'http://192.168.1.122:8000',
    # 'DOCUMENT_SERVER_URL': 'http://onlyoffice.first-iq.com:12280',
    'DOCUMENT_SERVER_URL': 'https://chat.first-iq.com/onlyoffice',

    # 🔧 企业网盘地址（服务器 1，OnlyOffice 会回调这个地址）
    # 必须是 OnlyOffice 服务器能访问的地址
    # 'SERVER_URL': 'http://192.168.1.130:10900',
    'SERVER_URL': 'https://chat.first-iq.com',
    'CLOUD_SERVER_URL': 'https://chat.first-iq.com/cloud/',

    # 🔧 JWT 密钥（必须与服务器 2 的 JWT_SECRET 完全一致）
    'JWT_SECRET': config('JWT_SECRET'),

    # 是否启用 JWT
    'JWT_ENABLED': True,

    # JWT Header
    'JWT_HEADER': 'Authorization',

    # 支持的文件格式
    'WORD_FORMATS': ['.doc', '.docx', '.docm', '.dot', '.dotx', '.dotm', '.odt', '.ott', '.rtf', '.txt',
                     '.html', '.htm', '.mht', '.pdf', '.fb2', '.epub', '.xps',
                     ],
    'EXCEL_FORMATS': ['.xls', '.xlsx', '.xlsm', '.xlt', '.xltx', '.xltm', '.ods', '.ots', '.csv', ],
    'PPT_FORMATS': ['.pps', '.ppsx', '.ppsm', '.ppt', '.pptx', '.pptm', '.pot', '.potx', '.potm', '.odp', '.otp', ],
    'PDF_FORMATS': ['.pdf'],

    # 🔧 新增：文档版本和编辑锁配置
    'VERSION_KEEP_COUNT': 10,  # 保留最近 10 个版本
    'VERSION_KEEP_DAYS': 30,  # 保留 30 天
    'EDIT_LOCK_EXPIRE_MINUTES': 30,  # 编辑锁过期时间（分钟）

    # 🔧 聊天相关配置
    'CHAT_ENABLED': True,
    'CHAT_HISTORY_LIMIT': 100,
}

CHANNELS_ENABLED = True

# 允许同源 iframe 嵌套（管理控制台内嵌 OA 页面）
X_FRAME_OPTIONS = 'SAMEORIGIN'

# CORS_ALLOW_CREDENTIALS = True


# 聊天室系统设置

CACHE_PREFIX = 'company_chat:config:'  # ✅ 添加前缀避免冲突

# 🔧 预定义配置项（企业级聊天室核心配置）
PREDEFINED_CONFIGS = {
    # ==================== 基础设置 ====================
    'system.name': {
        'name': '系统名称',
        'value_type': 'string',
        'default': '企业聊天室',
        'description': '显示在页面标题和登录页的系统名称',
        'category': 'basic',
        'validation': {'min_length': 2, 'max_length': 50}
    },
    'system.logo_url': {
        'name': '系统 Logo',
        'value_type': 'string',
        'default': '/static/images/logo.png',
        'description': '系统标识图片的 URL 地址',
        'category': 'basic',
        'validation': {'pattern': r'^https?://.*\.(png|jpg|jpeg|svg)$'}
    },
    'system.maintenance_mode': {
        'name': '维护模式',
        'value_type': 'boolean',
        'default': 'false',
        'description': '开启后普通用户无法访问，仅管理员可用',
        'category': 'basic'
    },
    'system.user_registration_enabled': {
        'name': '用户注册',
        'value_type': 'boolean',
        'default': 'false',
        'description': '是否允许新用户自主注册',
        'category': 'basic'
    },
    'system.default_language': {
        'name': '默认语言',
        'value_type': 'string',
        'default': 'zh-CN',
        'description': '新用户默认界面语言',
        'category': 'basic',
        'choices': ['zh-CN', 'en-US', 'ja-JP']
    },
    'system.timezone': {
        'name': '默认时区',
        'value_type': 'string',
        'default': 'Asia/Shanghai',
        'description': '新用户默认时区设置',
        'category': 'basic'
    },

    # ==================== 聊天设置 ====================
    'chat.max_message_length': {
        'name': '消息最大长度',
        'value_type': 'integer',
        'default': '2000',
        'description': '单条消息允许的最大字符数',
        'category': 'chat',
        'validation': {'min': 100, 'max': 10000}
    },
    'chat.typing_timeout': {
        'name': '输入状态超时',
        'value_type': 'integer',
        'default': '5',
        'description': '输入状态显示超时时间（秒）',
        'category': 'chat',
        'validation': {'min': 1, 'max': 30}
    },
    'chat.message_retention_days': {
        'name': '消息保留天数',
        'value_type': 'integer',
        'default': '365',
        'description': '消息自动清理保留天数（0=永久保留）',
        'category': 'chat',
        'validation': {'min': 0, 'max': 3650}
    },
    'chat.message_canrevoke_minutes': {
        'name': '消息撤回时间',
        'value_type': 'integer',
        'default': '10',
        'description': '消息可撤回时间（分钟）',
        'category': 'chat',
        'validation': {'min': 1, 'max': 60}
    },
    'chat.read_receipt_enabled': {
        'name': '已读回执',
        'value_type': 'boolean',
        'default': 'true',
        'description': '是否显示消息已读状态',
        'category': 'chat'
    },
    'chat.history_sync_enabled': {
        'name': '历史消息同步',
        'value_type': 'boolean',
        'default': 'true',
        'description': '新设备登录时是否同步历史消息',
        'category': 'chat'
    },
    'chat.emoji_enabled': {
        'name': '表情功能',
        'value_type': 'boolean',
        'default': 'true',
        'description': '是否启用表情发送功能',
        'category': 'chat'
    },

    # ==================== 文件设置 ====================
    'file.max_upload_size_mb': {
        'name': '文件上传总上限',
        'value_type': 'integer',
        'default': '50',
        'description': '单个文件允许的最大上传大小（MB）',
        'category': 'file',
        'validation': {'min': 1, 'max': 1024}
    },
    'file.image_max_size_mb': {
        'name': '图片大小上限',
        'value_type': 'integer',
        'default': '20',
        'description': '图片文件允许的最大大小（MB）',
        'category': 'file',
        'validation': {'min': 1, 'max': 500}
    },
    'file.video_max_size_mb': {
        'name': '视频大小上限',
        'value_type': 'integer',
        'default': '100',
        'description': '视频文件允许的最大大小（MB）',
        'category': 'file',
        'validation': {'min': 10, 'max': 2048}
    },
    'file.audio_max_size_mb': {
        'name': '音频大小上限',
        'value_type': 'integer',
        'default': '30',
        'description': '音频文件允许的最大大小（MB）',
        'category': 'file',
        'validation': {'min': 1, 'max': 500}
    },
    'file.allowed_types': {
        'name': '允许的文件类型',
        'value_type': 'json',
        'default': '["image", "video", "audio", "file"]',
        'description': '允许上传的文件类型列表',
        'category': 'file',
        'validation': {'is_array': True}
    },
    'file.image_formats': {
        'name': '允许的图片格式',
        'value_type': 'json',
        'default': '["jpg", "jpeg", "png", "gif", "webp"]',
        'description': '允许上传的图片文件格式',
        'category': 'file'
    },
    'file.video_formats': {
        'name': '允许的视频格式',
        'value_type': 'json',
        'default': '["mp4", "webm", "mov"]',
        'description': '允许上传的视频文件格式',
        'category': 'file'
    },

    # ==================== 语音设置 ====================
    'voice.max_duration_seconds': {
        'name': '语音消息最大时长',
        'value_type': 'integer',
        'default': '60',
        'description': '语音消息允许的最大录制时长（秒）',
        'category': 'voice',
        'validation': {'min': 10, 'max': 300}
    },
    'voice.min_duration_seconds': {
        'name': '语音消息最小时长',
        'value_type': 'integer',
        'default': '1',
        'description': '语音消息允许的最小录制时长（秒）',
        'category': 'voice',
        'validation': {'min': 1, 'max': 10}
    },
    'voice.allowed_formats': {
        'name': '语音格式',
        'value_type': 'json',
        'default': '["webm", "mp3", "m4a", "ogg"]',
        'description': '允许的语音文件格式',
        'category': 'voice'
    },
    'voice.auto_transcribe': {
        'name': '语音转文字',
        'value_type': 'boolean',
        'default': 'false',
        'description': '是否自动将语音消息转换为文字',
        'category': 'voice'
    },

    # ==================== 安全设置 ====================
    'security.login_max_attempts': {
        'name': '登录最大尝试次数',
        'value_type': 'integer',
        'default': '5',
        'description': '连续登录失败最大次数后锁定账户',
        'category': 'security',
        'validation': {'min': 3, 'max': 20}
    },
    'security.login_lockout_minutes': {
        'name': '登录锁定时间',
        'value_type': 'integer',
        'default': '15',
        'description': '登录失败锁定账户的时长（分钟）',
        'category': 'security',
        'validation': {'min': 5, 'max': 1440}
    },
    'security.session_timeout_hours': {
        'name': '会话超时时间',
        'value_type': 'integer',
        'default': '24',
        'description': '用户会话无操作超时时间（小时）',
        'category': 'security',
        'validation': {'min': 1, 'max': 168}
    },
    'security.password_min_length': {
        'name': '密码最小长度',
        'value_type': 'integer',
        'default': '8',
        'description': '用户密码要求的最小长度',
        'category': 'security',
        'validation': {'min': 6, 'max': 32}
    },
    'security.password_require_special': {
        'name': '密码特殊字符',
        'value_type': 'boolean',
        'default': 'true',
        'description': '密码是否必须包含特殊字符',
        'category': 'security'
    },
    'security.sensitive_words': {
        'name': '敏感词过滤',
        'value_type': 'json',
        'default': '[]',
        'description': '消息内容敏感词列表（正则表达式）',
        'category': 'security',
        'validation': {'is_array': True}
    },

    # ==================== 通知设置 ====================
    'notification.desktop_enabled': {
        'name': '桌面通知',
        'value_type': 'boolean',
        'default': 'true',
        'description': '是否启用浏览器桌面通知',
        'category': 'notification'
    },
    'notification.sound_enabled': {
        'name': '声音提醒',
        'value_type': 'boolean',
        'default': 'true',
        'description': '是否启用新消息声音提醒',
        'category': 'notification'
    },
    'notification.vibrate_enabled': {
        'name': '震动提醒',
        'value_type': 'boolean',
        'default': 'true',
        'description': '是否启用移动端震动提醒',
        'category': 'notification'
    },
    'notification.mention_sound': {
        'name': '@提醒声音',
        'value_type': 'boolean',
        'default': 'true',
        'description': '@提及是否使用特殊提醒音',
        'category': 'notification'
    },
    'notification.badge_enabled': {
        'name': '角标显示',
        'value_type': 'boolean',
        'default': 'true',
        'description': '是否在浏览器标签显示未读数角标',
        'category': 'notification'
    },

    # ==================== 高级设置 ====================
    'advanced.cache_ttl_seconds': {
        'name': '缓存过期时间',
        'value_type': 'integer',
        'default': '300',
        'description': '系统缓存默认过期时间（秒）',
        'category': 'advanced',
        'validation': {'min': 60, 'max': 86400}
    },
    'advanced.api_rate_limit': {
        'name': 'API 限流',
        'value_type': 'integer',
        'default': '100',
        'description': '每用户每分钟最大请求次数',
        'category': 'advanced',
        'validation': {'min': 10, 'max': 1000}
    },
    'advanced.log_level': {
        'name': '日志级别',
        'value_type': 'string',
        'default': 'INFO',
        'description': '系统日志记录级别',
        'category': 'advanced',
        'choices': ['DEBUG', 'INFO', 'WARNING', 'ERROR']
    },
    'advanced.enable_compression': {
        'name': '响应压缩',
        'value_type': 'boolean',
        'default': 'true',
        'description': '是否启用响应数据压缩',
        'category': 'advanced'
    },
}

# 配置分类定义
CONFIG_CATEGORIES = [
    {'key': 'basic', 'name': '基础设置', 'icon': 'fas fa-cog', 'order': 1},
    {'key': 'chat', 'name': '聊天设置', 'icon': 'fas fa-comments', 'order': 2},
    {'key': 'file', 'name': '文件设置', 'icon': 'fas fa-file', 'order': 3},
    {'key': 'voice', 'name': '语音设置', 'icon': 'fas fa-microphone', 'order': 4},
    {'key': 'security', 'name': '安全设置', 'icon': 'fas fa-shield-alt', 'order': 5},
    {'key': 'notification', 'name': '通知设置', 'icon': 'fas fa-bell', 'order': 6},
    {'key': 'advanced', 'name': '高级设置', 'icon': 'fas fa-sliders-h', 'order': 7},
]


TURN_SECRET = config('TURN_SECRET')
TURN_REALM = config('TURN_REALM')

# 百度地图key
BAIDU_MAP_SERVER_AK = config('BAIDU_MAP_SERVER_AK')

# 百度OCR（票据识别）
BAIDU_OCR_API_KEY = config('BAIDU_OCR_API_KEY', default='')
BAIDU_OCR_SECRET_KEY = config('BAIDU_OCR_SECRET_KEY', default='')

# ===== Web Push (VAPID) =====
VAPID_PUBLIC_KEY = config('VAPID_PUBLIC_KEY', default='')
VAPID_PRIVATE_KEY = config('VAPID_PRIVATE_KEY', default='')
VAPID_ADMIN_EMAIL = config('VAPID_ADMIN_EMAIL', default='admin@first-iq.com')
PUSH_ENABLED = bool(VAPID_PUBLIC_KEY and VAPID_PRIVATE_KEY)
print(f'PUSH_ENABLED: {PUSH_ENABLED}')

# 🔧 FCM（安卓/鸿蒙）代理：国内服务器无法直连 Google 的 fcm.googleapis.com 时，
# 在 .env 里配置一个可用的 HTTP(S) 代理（如企业代理）即可让安卓/鸿蒙收到推送。
PUSH_PROXY = config('PUSH_PROXY', default='')

# 🔧 海外推送中继：在不使用代理时，把 FCM 推送转发给海外中继服务发送
# （见项目根目录 push_relay.py）。PUSH_RELAY_SECRET 需与中继端配置一致。
PUSH_RELAY_URL = config('PUSH_RELAY_URL', default='')
PUSH_RELAY_SECRET = config('PUSH_RELAY_SECRET', default='')


# 火山方舟大模型API_KEY
ARK_API_KEY = config('ARK_API_KEY', default='')
# 火山方舟模型名（或推理接入点 ID ep-xxx），如豆包模型 doubao-seed-1-6-250615 / doubao-pro-32k
ARK_MODEL = config('ARK_MODEL', default='doubao-seed-2-0-lite-260428')