# Generated by Django 3.2.25 on 2026-07-16 04:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='群聊名称')),
                ('room_type', models.CharField(choices=[('private', '私聊'), ('group', '群聊')], default='private', max_length=20, verbose_name='聊天类型')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='是否置顶')),
                ('is_muted', models.BooleanField(default=False, verbose_name='是否免打扰')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_rooms', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('members', models.ManyToManyField(related_name='chat_rooms', to=settings.AUTH_USER_MODEL, verbose_name='成员')),
            ],
            options={
                'verbose_name': '聊天室',
                'verbose_name_plural': '聊天室',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('md5', models.CharField(max_length=32, unique=True, verbose_name='文件MD5')),
                ('file', models.FileField(upload_to='chat/uploads/', verbose_name='文件')),
                ('mp3_file', models.FileField(blank=True, null=True, upload_to='chat/uploads/mp3/', verbose_name='MP3格式文件')),
                ('mp3_converted', models.BooleanField(default=False, verbose_name='是否已转码为MP3')),
                ('mp3_status', models.CharField(choices=[('pending', '待转码'), ('converting', '转码中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='MP3转码状态')),
                ('duration', models.FloatField(blank=True, null=True, verbose_name='音频时长(秒)')),
                ('is_sync_to_cloud', models.BooleanField(default=False, verbose_name='是否已同步到云端')),
                ('filename', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('size', models.BigIntegerField(verbose_name='文件大小')),
                ('mime_type', models.CharField(max_length=100, verbose_name='MIME类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
            ],
            options={
                'verbose_name': '文件上传记录',
                'verbose_name_plural': '文件上传记录',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True, verbose_name='消息内容')),
                ('message_type', models.CharField(choices=[('text', '文本'), ('image', '图片'), ('file', '文件'), ('voice', '语音'), ('video', '视频'), ('emoji', '表情'), ('call_audio', '语音通话'), ('call_video', '视频通话'), ('task_card', '任务卡片')], default='text', max_length=20, verbose_name='消息类型')),
                ('quote_content', models.TextField(blank=True, verbose_name='引用内容')),
                ('quote_sender', models.CharField(blank=True, max_length=100, verbose_name='引用发送者')),
                ('quote_sender_id', models.IntegerField(blank=True, null=True, verbose_name='引用发送者ID')),
                ('quote_timestamp', models.DateTimeField(blank=True, null=True, verbose_name='引用消息时间戳')),
                ('quote_message_type', models.CharField(choices=[('text', '文本'), ('image', '图片'), ('file', '文件'), ('voice', '语音'), ('video', '视频'), ('emoji', '表情'), ('call_audio', '语音通话'), ('call_video', '视频通话'), ('task_card', '任务卡片')], default='text', max_length=20, verbose_name='引用消息类型')),
                ('mentioned_all', models.BooleanField(default=False, verbose_name='是否@全体成员')),
                ('voice_duration', models.FloatField(blank=True, null=True, verbose_name='语音时长(秒)')),
                ('call_duration', models.IntegerField(blank=True, null=True, verbose_name='通话时长(秒)')),
                ('call_type', models.CharField(blank=True, choices=[('audio', '语音通话'), ('video', '视频通话')], max_length=20, null=True, verbose_name='通话类型')),
                ('call_status', models.CharField(choices=[('completed', '已完成'), ('missed', '未接听'), ('rejected', '已拒绝'), ('cancelled', '已取消')], default='completed', max_length=20, verbose_name='通话状态')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
                ('chat_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatroom', verbose_name='聊天室')),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.fileupload', verbose_name='文件')),
                ('mentioned_users', models.ManyToManyField(blank=True, related_name='mentioned_in_messages', to=settings.AUTH_USER_MODEL, verbose_name='被提及的用户')),
                ('quote_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quoted_by', to='chat.message', verbose_name='引用的消息')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='发送者')),
            ],
            options={
                'verbose_name': '消息',
                'verbose_name_plural': '消息',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserOnlineStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_online', models.BooleanField(default=False, verbose_name='在线状态')),
                ('last_seen', models.DateTimeField(blank=True, null=True, verbose_name='最后在线时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='online_status', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户在线状态',
                'verbose_name_plural': '用户在线状态',
            },
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='配置键')),
                ('name', models.CharField(max_length=100, verbose_name='配置名称')),
                ('value', models.TextField(verbose_name='配置值')),
                ('value_type', models.CharField(choices=[('string', '字符串'), ('integer', '整数'), ('boolean', '布尔值'), ('float', '浮点数'), ('json', 'JSON 对象')], default='string', max_length=20, verbose_name='值类型')),
                ('category', models.CharField(choices=[('basic', '基础设置'), ('chat', '聊天设置'), ('file', '文件设置'), ('voice', '语音设置'), ('security', '安全设置'), ('notification', '通知设置'), ('advanced', '高级设置')], default='basic', max_length=30, verbose_name='分类')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('default_value', models.TextField(blank=True, verbose_name='默认值')),
                ('is_public', models.BooleanField(default=False, verbose_name='是否公开')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='最后更新人')),
            ],
            options={
                'verbose_name': '系统配置',
                'verbose_name_plural': '系统配置',
                'ordering': ['category', 'key'],
            },
        ),
        migrations.CreateModel(
            name='ChatRoomDeleteStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('chat_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delete_statuses', to='chat.chatroom', verbose_name='聊天室')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '聊天室删除状态',
                'verbose_name_plural': '聊天室删除状态',
            },
        ),
        migrations.CreateModel(
            name='MessageReadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True, verbose_name='阅读时间')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_statuses', to='chat.message', verbose_name='消息')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '消息阅读状态',
                'verbose_name_plural': '消息阅读状态',
                'unique_together': {('message', 'user')},
            },
        ),
        migrations.CreateModel(
            name='MessageDeleteStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delete_statuses', to='chat.message', verbose_name='消息')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '消息删除状态',
                'verbose_name_plural': '消息删除状态',
                'unique_together': {('message', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['chat_room', '-timestamp'], name='chat_messag_chat_ro_c77cb3_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', '-timestamp'], name='chat_messag_sender__b0f4ad_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_deleted', '-timestamp'], name='chat_messag_is_dele_64c758_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_read', 'chat_room'], name='chat_messag_is_read_1fa3ac_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['message_type', '-timestamp'], name='chat_messag_message_4ce30f_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['timestamp'], name='chat_messag_timesta_6494d7_idx'),
        ),
        migrations.AddIndex(
            model_name='fileupload',
            index=models.Index(fields=['md5'], name='chat_fileup_md5_a2cf43_idx'),
        ),
        migrations.AddIndex(
            model_name='fileupload',
            index=models.Index(fields=['uploaded_by'], name='chat_fileup_uploade_ed1143_idx'),
        ),
        migrations.AddIndex(
            model_name='fileupload',
            index=models.Index(fields=['mp3_status'], name='chat_fileup_mp3_sta_9c7654_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chatroomdeletestatus',
            unique_together={('chat_room', 'user')},
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['name'], name='chat_chatro_name_b0f383_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['room_type', 'updated_at'], name='chat_chatro_room_ty_29cc96_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['is_deleted', 'updated_at'], name='chat_chatro_is_dele_b62814_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['creator', '-updated_at'], name='chat_chatro_creator_75dc88_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['room_type', 'is_deleted', '-updated_at'], name='chat_chatro_room_ty_a545c4_idx'),
        ),
    ]
