# Generated by Django 4.2.7 on 2026-04-18 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='is_sync_to_cloud',
            field=models.BooleanField(default=False, verbose_name='是否已同步到云端'),
        ),
    ]
