# Generated by Django 4.2.30 on 2026-05-04 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_fileupload_is_sync_to_cloud'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='mentioned_all',
            field=models.BooleanField(default=False, verbose_name='是否@全体成员'),
        ),
    ]
