# Generated by Django 4.2.30 on 2026-05-16 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_mentioned_all'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='call_duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='通话时长(秒)'),
        ),
        migrations.AddField(
            model_name='message',
            name='call_status',
            field=models.CharField(choices=[('completed', '已完成'), ('missed', '未接听'), ('rejected', '已拒绝'), ('cancelled', '已取消')], default='completed', max_length=20, verbose_name='通话状态'),
        ),
        migrations.AddField(
            model_name='message',
            name='call_type',
            field=models.CharField(blank=True, choices=[('audio', '语音通话'), ('video', '视频通话')], max_length=20, null=True, verbose_name='通话类型'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', '文本'), ('image', '图片'), ('file', '文件'), ('voice', '语音'), ('video', '视频'), ('emoji', '表情'), ('call_audio', '语音通话'), ('call_video', '视频通话')], default='text', max_length=20, verbose_name='消息类型'),
        ),
        migrations.AlterField(
            model_name='message',
            name='quote_message_type',
            field=models.CharField(choices=[('text', '文本'), ('image', '图片'), ('file', '文件'), ('voice', '语音'), ('video', '视频'), ('emoji', '表情'), ('call_audio', '语音通话'), ('call_video', '视频通话')], default='text', max_length=20, verbose_name='引用消息类型'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['room_type', 'is_deleted', '-updated_at'], name='chat_chatro_room_ty_a545c4_idx'),
        ),
    ]
