# Generated by Django 4.2.30 on 2026-06-27 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_message_call_duration_message_call_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', '文本'), ('image', '图片'), ('file', '文件'), ('voice', '语音'), ('video', '视频'), ('emoji', '表情'), ('call_audio', '语音通话'), ('call_video', '视频通话'), ('task_card', '任务卡片')], default='text', max_length=20, verbose_name='消息类型'),
        ),
        migrations.AlterField(
            model_name='message',
            name='quote_message_type',
            field=models.CharField(choices=[('text', '文本'), ('image', '图片'), ('file', '文件'), ('voice', '语音'), ('video', '视频'), ('emoji', '表情'), ('call_audio', '语音通话'), ('call_video', '视频通话'), ('task_card', '任务卡片')], default='text', max_length=20, verbose_name='引用消息类型'),
        ),
    ]
