# Generated by Django 4.2.30 on 2026-06-16 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_email_verified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='公司名称')),
                ('contact_name', models.CharField(max_length=100, verbose_name='联系人姓名')),
                ('email', models.EmailField(max_length=254, verbose_name='企业邮箱')),
                ('phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('demand_type', models.CharField(choices=[('private', '私有化部署'), ('saas', 'SaaS 云端订阅'), ('custom', '深度定制开发'), ('poc', '申请免费 POC 测试环境')], default='private', max_length=20, verbose_name='期望部署方式')),
                ('message', models.TextField(blank=True, null=True, verbose_name='需求描述')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('contacted', '已联系'), ('closed', '已关闭')], default='pending', max_length=20, verbose_name='处理状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('handled_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('admin_notes', models.TextField(blank=True, null=True, verbose_name='管理员备注')),
            ],
            options={
                'verbose_name': '咨询请求',
                'verbose_name_plural': '咨询请求',
                'ordering': ['-created_at'],
            },
        ),
    ]
