# Generated by Django 3.2.25 on 2026-07-20 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_message_message_type_and_more'),
        ('accounts', '0004_loginlog_operationlog_customuser_is_staff_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='企业名称')),
                ('short_name', models.CharField(blank=True, max_length=50, verbose_name='企业简称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='企业编码')),
                ('logo', models.ImageField(blank=True, upload_to='tenants/logos/', verbose_name='企业Logo')),
                ('tenant_type', models.CharField(choices=[('group', '集团'), ('company', '公司'), ('branch', '分公司'), ('virtual', '虚拟组织')], default='company', max_length=20, verbose_name='企业类型')),
                ('level', models.IntegerField(default=1, verbose_name='层级')),
                ('industry', models.CharField(blank=True, max_length=100, verbose_name='所属行业')),
                ('scale', models.CharField(blank=True, max_length=50, verbose_name='企业规模')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='企业地址')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('website', models.URLField(blank=True, verbose_name='企业官网')),
                ('description', models.TextField(blank=True, verbose_name='企业简介')),
                ('max_users', models.IntegerField(default=100, verbose_name='最大用户数')),
                ('max_storage_gb', models.IntegerField(default=10, verbose_name='最大存储空间(GB)')),
                ('features', models.JSONField(blank=True, default=dict, verbose_name='功能开关')),
                ('custom_domain', models.CharField(blank=True, max_length=200, verbose_name='自定义域名')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_verified', models.BooleanField(default=False, verbose_name='是否已认证')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '企业/租户',
                'verbose_name_plural': '企业/租户',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TenantMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', '企业所有者'), ('admin', '企业管理员'), ('dept_admin', '部门管理员'), ('member', '普通成员')], default='member', max_length=20, verbose_name='企业角色')),
                ('nickname', models.CharField(blank=True, max_length=100, verbose_name='企业内昵称')),
                ('employee_id', models.CharField(blank=True, max_length=50, verbose_name='工号')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认企业')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('left_at', models.DateTimeField(blank=True, null=True, verbose_name='离开时间')),
            ],
            options={
                'verbose_name': '用户企业关联',
                'verbose_name_plural': '用户企业关联',
            },
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': '部门', 'verbose_name_plural': '部门'},
        ),
        migrations.AddField(
            model_name='department',
            name='auto_create_group',
            field=models.BooleanField(default=True, verbose_name='自动创建部门群'),
        ),
        migrations.AddField(
            model_name='department',
            name='auto_sync_members',
            field=models.BooleanField(default=True, verbose_name='自动同步成员到群'),
        ),
        migrations.AddField(
            model_name='department',
            name='department_group',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department', to='chat.chatroom', verbose_name='部门群聊'),
        ),
        migrations.AddField(
            model_name='department',
            name='department_type',
            field=models.CharField(choices=[('company', '公司'), ('department', '部门'), ('group', '小组'), ('virtual', '虚拟组织')], default='department', max_length=20, verbose_name='部门类型'),
        ),
        migrations.AddField(
            model_name='department',
            name='deputy_managers',
            field=models.ManyToManyField(blank=True, related_name='deputy_managed_departments', to=settings.AUTH_USER_MODEL, verbose_name='副负责人'),
        ),
        migrations.AddField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True, verbose_name='部门描述'),
        ),
        migrations.AddField(
            model_name='department',
            name='full_path',
            field=models.CharField(blank=True, help_text='如：公司/技术部/后端组', max_length=500, verbose_name='完整路径'),
        ),
        migrations.AddField(
            model_name='department',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
        migrations.AddField(
            model_name='department',
            name='level',
            field=models.IntegerField(default=1, verbose_name='层级'),
        ),
        migrations.AddField(
            model_name='department',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='排序号'),
        ),
        migrations.AddField(
            model_name='department',
            name='tags',
            field=models.JSONField(blank=True, default=list, verbose_name='部门标签'),
        ),
        migrations.AddField(
            model_name='department',
            name='visibility',
            field=models.CharField(choices=[('public', '全企业可见'), ('department', '仅本部门及子部门可见'), ('custom', '自定义可见范围'), ('hidden', '隐藏部门')], default='public', max_length=20, verbose_name='可见范围'),
        ),
        migrations.AddField(
            model_name='department',
            name='visible_departments',
            field=models.ManyToManyField(blank=True, related_name='visible_by', to='accounts.Department', verbose_name='可见部门列表'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, verbose_name='部门名称'),
        ),
        migrations.AlterField(
            model_name='department',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='accounts.department', verbose_name='上级部门'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['tenant', 'parent', 'is_active'], name='accounts_de_tenant__743324_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['tenant', 'code'], name='accounts_de_tenant__ba2062_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['tenant', 'level'], name='accounts_de_tenant__a94b53_idx'),
        ),
        migrations.AddField(
            model_name='tenantmembership',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='accounts.tenant', verbose_name='企业'),
        ),
        migrations.AddField(
            model_name='tenantmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_memberships', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_tenants', to=settings.AUTH_USER_MODEL, verbose_name='企业所有者'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_tenants', to='accounts.tenant', verbose_name='上级企业/集团'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='active_tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_users', to='accounts.tenant', verbose_name='当前激活企业'),
        ),
        migrations.AddField(
            model_name='department',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='accounts.tenant', verbose_name='所属企业'),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('tenant', 'name', 'parent')},
        ),
        migrations.AddIndex(
            model_name='tenantmembership',
            index=models.Index(fields=['user', 'is_active'], name='accounts_te_user_id_c6cf37_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantmembership',
            index=models.Index(fields=['tenant', 'role'], name='accounts_te_tenant__5e1e1d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tenantmembership',
            unique_together={('user', 'tenant')},
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['code'], name='accounts_te_code_9d6d39_idx'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['parent', 'is_active'], name='accounts_te_parent__abff9e_idx'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['tenant_type'], name='accounts_te_tenant__34a707_idx'),
        ),
    ]
