# Generated by Django 3.2.25 on 2026-07-30 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20260720_1814'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenantmembership',
            options={'ordering': ['-joined_at'], 'verbose_name': '用户企业关联', 'verbose_name_plural': '用户企业关联'},
        ),
        migrations.AddField(
            model_name='department',
            name='converted_tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_from_departments', to='accounts.tenant', verbose_name='转换后的企业'),
        ),
    ]
