# Generated by Django 4.2.30 on 2026-06-27 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_message_call_duration_message_call_status_and_more'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='related_chat_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task', to='chat.chatroom', verbose_name='来源聊天室'),
        ),
        migrations.AlterField(
            model_name='task',
            name='related_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task', to='chat.message', verbose_name='来源消息'),
        ),
    ]
