from django.urls import path
from .views import AttendanceViewSet, ApprovalViewSet, ApprovalTypeViewSet, WorkNotificationViewSet, SubsidyViewSet, WorkCalendarViewSet, MaterialViewSet, DailyWorkSummaryViewSet, AnnouncementViewSet

urlpatterns = [
    # 集团公告
    path('announcements/', AnnouncementViewSet.as_view({'get': 'list', 'post': 'create'}), name='announcement-list'),
    path('announcements/<int:pk>/', AnnouncementViewSet.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy'}), name='announcement-detail'),
    path('announcements/<int:pk>/publish/', AnnouncementViewSet.as_view({'post': 'publish'}), name='announcement-publish'),
    path('announcements/<int:pk>/comments/', AnnouncementViewSet.as_view({'get': 'comments'}), name='announcement-comments'),
    path('announcements/<int:pk>/add-comment/', AnnouncementViewSet.as_view({'post': 'add_comment'}), name='announcement-add-comment'),

    # 考勤打卡
    path('attendance/clock-in/', AttendanceViewSet.as_view({'post': 'clock_in'}), name='attendance-clock-in'),
    path('attendance/clock-out/', AttendanceViewSet.as_view({'post': 'clock_out'}), name='attendance-clock-out'),
    path('attendance/makeup/', AttendanceViewSet.as_view({'post': 'makeup'}), name='attendance-makeup'),
    path('attendance/today/', AttendanceViewSet.as_view({'get': 'today'}), name='attendance-today'),
    path('attendance/statistics/', AttendanceViewSet.as_view({'get': 'statistics'}), name='attendance-statistics'),
    path('attendance/export/', AttendanceViewSet.as_view({'get': 'export'}), name='attendance-export'),
    path('attendance/', AttendanceViewSet.as_view({'get': 'list'}), name='attendance-list'),
    path('attendance/<int:pk>/', AttendanceViewSet.as_view({'get': 'retrieve'}), name='attendance-detail'),
    path('attendance/<int:pk>/convert-coords/', AttendanceViewSet.as_view({'get': 'convert_coords'}), name='attendance-convert-coords'),
    path('attendance/attendance-configs/', AttendanceViewSet.as_view({'get': 'attendance_configs'}), name='attendance-configs'),
    path('attendance/save-attendance-config/', AttendanceViewSet.as_view({'post': 'save_attendance_config'}), name='save-attendance-config'),
    path('attendance/delete-attendance-config/<int:pk>/', AttendanceViewSet.as_view({'delete': 'delete_attendance_config'}), name='delete-attendance-config'),
    path('attendance/my-config/', AttendanceViewSet.as_view({'get': 'resolve_my_config'}), name='resolve-my-config'),
    path('attendance/members/', AttendanceViewSet.as_view({'get': 'members'}), name='attendance-members'),
    path('attendance/user-attendance-configs/', AttendanceViewSet.as_view({'get': 'user_attendance_configs'}), name='attendance-user-configs'),
    path('attendance/save-user-attendance-config/', AttendanceViewSet.as_view({'post': 'save_user_attendance_config'}), name='save-user-attendance-config'),
    path('attendance/delete-user-attendance-config/<int:pk>/', AttendanceViewSet.as_view({'delete': 'delete_user_attendance_config'}), name='delete-user-attendance-config'),
    path('attendance/calendar-stats/', AttendanceViewSet.as_view({'get': 'calendar_stats'}), name='attendance-calendar-stats'),
    # 兼容旧版前端调用的下划线写法（calendar_stats）
    path('attendance/calendar_stats/', AttendanceViewSet.as_view({'get': 'calendar_stats'}), name='attendance-calendar-stats-alias'),
    path('attendance/calendar-day-detail/', AttendanceViewSet.as_view({'get': 'calendar_day_detail'}), name='attendance-calendar-day-detail'),

    # OA审批
    path('approval/approval_chain/', ApprovalViewSet.as_view({'get': 'approval_chain'}), name='approval-approval-chain'),
    path('approval/geocode/', ApprovalViewSet.as_view({'get': 'geocode'}), name='approval-geocode'),
    path('approval/admins/', ApprovalViewSet.as_view({'get': 'admins'}), name='approval-admins'),
    path('approval/departments/', ApprovalViewSet.as_view({'get': 'departments'}), name='approval-departments'),
    path('approval/all-departments/', ApprovalViewSet.as_view({'get': 'all_departments'}), name='approval-all-departments'),
    path('approval/org_departments/', ApprovalViewSet.as_view({'get': 'org_departments'}), name='approval-org-departments'),
    path('approval/upload-attachment/', ApprovalViewSet.as_view({'post': 'upload_attachment'}), name='approval-upload'),
    path('approval/dept-configs/', ApprovalViewSet.as_view({'get': 'dept_configs'}), name='approval-dept-configs'),
    path('approval/save-dept-config/', ApprovalViewSet.as_view({'post': 'save_dept_config'}), name='approval-save-dept-config'),
    path('approval/delete-dept-config/<int:pk>/', ApprovalViewSet.as_view({'delete': 'delete_dept_config'}), name='approval-delete-dept-config'),
    path('approval/finance-specialists/', ApprovalViewSet.as_view({'get': 'finance_specialists', 'post': 'finance_specialists'}), name='approval-finance-specialists'),
    path('approval/finance-specialists/<int:pk>/', ApprovalViewSet.as_view({'put': 'finance_specialist_detail', 'delete': 'finance_specialist_detail'}), name='approval-finance-specialist-detail'),
    path('approval/finance-specialist-users/', ApprovalViewSet.as_view({'get': 'finance_specialist_users'}), name='approval-finance-specialist-users'),
    path('approval/search-cc-users/', ApprovalViewSet.as_view({'get': 'search_cc_users'}), name='approval-search-cc-users'),
    path('approval/search-cc-departments/', ApprovalViewSet.as_view({'get': 'search_cc_departments'}), name='approval-search-cc-departments'),
    path('approval/my-pending/', ApprovalViewSet.as_view({'get': 'my_pending'}), name='approval-my-pending'),
    path('approval/draft/', ApprovalViewSet.as_view({'post': 'draft'}), name='approval-draft'),
    path('approval/drafts/', ApprovalViewSet.as_view({'get': 'drafts'}), name='approval-drafts'),

    # 审批类型管理（动态自定义类型）
    path('approval/types/', ApprovalTypeViewSet.as_view({'get': 'list', 'post': 'create'}), name='approval-types'),
    path('approval/types/<int:pk>/', ApprovalTypeViewSet.as_view({'put': 'update', 'patch': 'update', 'delete': 'destroy'}), name='approval-type-detail'),
    path('approval/', ApprovalViewSet.as_view({'get': 'list', 'post': 'create'}), name='approval-list'),
    path('approval/<int:pk>/', ApprovalViewSet.as_view({'get': 'retrieve'}), name='approval-detail'),
    path('approval/<int:pk>/approve/', ApprovalViewSet.as_view({'post': 'approve'}), name='approval-approve'),
    path('approval/<int:pk>/reject/', ApprovalViewSet.as_view({'post': 'reject'}), name='approval-reject'),
    path('approval/<int:pk>/deferred/', ApprovalViewSet.as_view({'post': 'deferred'}), name='approval-deferred'),
    path('approval/<int:pk>/processing/', ApprovalViewSet.as_view({'post': 'processing'}), name='approval-processing'),
    path('approval/<int:pk>/cancel/', ApprovalViewSet.as_view({'post': 'cancel'}), name='approval-cancel'),
    path('approval/<int:pk>/re-edit/', ApprovalViewSet.as_view({'post': 're_edit'}), name='approval-re-edit'),
    path('approval/<int:pk>/delete-draft/', ApprovalViewSet.as_view({'delete': 'delete_draft'}), name='approval-delete-draft'),
    path('approval/<int:pk>/update-draft/', ApprovalViewSet.as_view({'post': 'update_draft'}), name='approval-update-draft'),
    path('approval/<int:pk>/send-private/', ApprovalViewSet.as_view({'post': 'send_private'}), name='approval-send_private'),
    path('approval/<int:pk>/upload-receipt/', ApprovalViewSet.as_view({'post': 'upload_receipt'}), name='approval-upload-receipt'),
    path('approval/<int:pk>/delete-receipt/', ApprovalViewSet.as_view({'post': 'delete_receipt'}), name='approval-delete-receipt'),
    path('approval/custom-payment-methods/', ApprovalViewSet.as_view({'get': 'custom_payment_methods', 'post': 'custom_payment_methods'}), name='approval-custom-payment-methods'),
    path('approval/custom-payment-method/<int:pk>/', ApprovalViewSet.as_view({'delete': 'custom_payment_method'}), name='approval-custom-payment-method'),

    # 财务服务 - 员工消费普惠补贴
    path('subsidy/', SubsidyViewSet.as_view({'get': 'list', 'post': 'create'}), name='subsidy-list'),
    path('subsidy/upload-invoice/', SubsidyViewSet.as_view({'post': 'upload_invoice'}), name='subsidy-upload-invoice'),
    path('subsidy/upload-voucher/', SubsidyViewSet.as_view({'post': 'upload_voucher'}), name='subsidy-upload-voucher'),
    path('subsidy/upload-proof/', SubsidyViewSet.as_view({'post': 'upload_proof'}), name='subsidy-upload-proof'),
    path('subsidy/payment-info/', SubsidyViewSet.as_view({'get': 'payment_info', 'post': 'payment_info'}), name='subsidy-payment-info'),
    path('subsidy/ocr-invoice/', SubsidyViewSet.as_view({'post': 'ocr_invoice'}), name='subsidy-ocr-invoice'),
    path('subsidy/qr-scan/', SubsidyViewSet.as_view({'post': 'qr_scan'}), name='subsidy-qr-scan'),
    path('subsidy/ocr-status/', SubsidyViewSet.as_view({'get': 'ocr_status'}), name='subsidy-ocr-status'),
    path('subsidy/invoice-preview/', SubsidyViewSet.as_view({'get': 'invoice_preview'}), name='subsidy-invoice-preview'),
    path('subsidy/account/', SubsidyViewSet.as_view({'get': 'account'}), name='subsidy-account'),
    path('subsidy/wallet/', SubsidyViewSet.as_view({'get': 'wallet'}), name='subsidy-wallet'),
    path('subsidy/withdraw/', SubsidyViewSet.as_view({'post': 'withdraw'}), name='subsidy-withdraw'),
    path('subsidy/withdrawals/', SubsidyViewSet.as_view({'get': 'withdrawals'}), name='subsidy-withdrawals'),
    path('subsidy/withdrawals/all/', SubsidyViewSet.as_view({'get': 'withdrawals_all'}), name='subsidy-withdrawals-all'),
    path('subsidy/withdrawals/export/', SubsidyViewSet.as_view({'get': 'withdrawals_export'}), name='subsidy-withdrawals-export'),
    path('subsidy/withdrawals/<int:pk>/', SubsidyViewSet.as_view({'get': 'withdraw_detail'}), name='subsidy-withdraw-detail'),
    path('subsidy/withdrawals/<int:pk>/pay/', SubsidyViewSet.as_view({'post': 'withdraw_pay'}), name='subsidy-withdraw-pay'),
    path('subsidy/withdrawals/<int:pk>/reject/', SubsidyViewSet.as_view({'post': 'withdraw_reject'}), name='subsidy-withdraw-reject'),
    path('subsidy/payments/', SubsidyViewSet.as_view({'get': 'payments'}), name='subsidy-payments'),
    path('subsidy/all/', SubsidyViewSet.as_view({'get': 'all'}), name='subsidy-all'),
    path('subsidy/export/', SubsidyViewSet.as_view({'get': 'export'}), name='subsidy-export'),
    path('subsidy/configs/', SubsidyViewSet.as_view({'get': 'configs'}), name='subsidy-configs'),
    path('subsidy/save-config/', SubsidyViewSet.as_view({'post': 'save_config'}), name='subsidy-save-config'),
    path('subsidy/delete-config/<int:pk>/', SubsidyViewSet.as_view({'delete': 'delete_config'}), name='subsidy-delete-config'),
    path('subsidy/clear-ocr-cache/', SubsidyViewSet.as_view({'post': 'clear_ocr_cache'}), name='subsidy-clear-ocr-cache'),
    path('subsidy/<int:pk>/', SubsidyViewSet.as_view({'get': 'retrieve'}), name='subsidy-detail'),
    path('subsidy/<int:pk>/re-submit/', SubsidyViewSet.as_view({'post': 're_submit'}), name='subsidy-re-submit'),
    path('subsidy/<int:pk>/delete-my/', SubsidyViewSet.as_view({'delete': 'delete_my'}), name='subsidy-delete-my'),
    path('subsidy/<int:pk>/verify/', SubsidyViewSet.as_view({'post': 'verify'}), name='subsidy-verify'),
    path('subsidy/<int:pk>/verify-invoice/', SubsidyViewSet.as_view({'post': 'verify_invoice'}), name='subsidy-verify-invoice'),
    path('subsidy/<int:pk>/invoice-verify-status/', SubsidyViewSet.as_view({'get': 'invoice_verify_status'}), name='subsidy-invoice-verify-status'),
    path('subsidy/<int:pk>/update-invoice-type/', SubsidyViewSet.as_view({'post': 'update_invoice_type'}), name='subsidy-update-invoice-type'),

    # 工作日历 + 每日工作汇总通知
    path('work-calendar/', WorkCalendarViewSet.as_view({'get': 'list'}), name='work-calendar'),
    path('work-calendar/day/', WorkCalendarViewSet.as_view({'get': 'day'}), name='work-calendar-day'),
    path('work-calendar/stats/', WorkCalendarViewSet.as_view({'get': 'stats'}), name='work-calendar-stats'),
    path('work-calendar/approval-efficiency/', WorkCalendarViewSet.as_view({'get': 'approval_efficiency'}), name='work-calendar-approval-efficiency'),
    path('work-calendar/approval-leaderboard/', WorkCalendarViewSet.as_view({'get': 'approval_leaderboard'}), name='work-calendar-approval-leaderboard'),
    path('work-calendar/work-summary-stats/', WorkCalendarViewSet.as_view({'get': 'work_summary_stats'}), name='work-calendar-work-summary-stats'),
    path('work-calendar/org-activity/', WorkCalendarViewSet.as_view({'get': 'org_activity'}), name='work-calendar-org-activity'),
    path('work-calendar/member-search/', WorkCalendarViewSet.as_view({'get': 'member_search'}), name='work-calendar-member-search'),
    path('work-calendar/digest-config/', WorkCalendarViewSet.as_view({'get': 'digest_config', 'post': 'digest_config'}), name='work-calendar-digest-config'),
    path('work-calendar/digest-send/', WorkCalendarViewSet.as_view({'post': 'digest_send'}), name='work-calendar-digest-send'),

    # 物资管理（物品库 + 需求/领用联动 + 入库确认）
    path('material/items/', MaterialViewSet.as_view({'get': 'items', 'post': 'create_item'}), name='material-items'),
    path('material/item-search/', MaterialViewSet.as_view({'get': 'item_search'}), name='material-item-search'),
    path('material/items/<int:pk>/', MaterialViewSet.as_view({'get': 'retrieve_item', 'put': 'update_item', 'delete': 'delete_item'}), name='material-item-detail'),
    path('material/requirement-search/', MaterialViewSet.as_view({'get': 'requirement_search'}), name='material-requirement-search'),
    path('material/requirement-detail/', MaterialViewSet.as_view({'get': 'requirement_detail'}), name='material-requirement-detail'),
    path('material/stock-in/', MaterialViewSet.as_view({'post': 'stock_in'}), name='material-stock-in'),
    path('material/requirements/', MaterialViewSet.as_view({'get': 'requirements'}), name='material-requirements'),
    path('material/requisitions/', MaterialViewSet.as_view({'get': 'requisitions'}), name='material-requisitions'),
    path('material/requirement-status/', MaterialViewSet.as_view({'post': 'requirement_status'}), name='material-requirement-status'),

    # 每日工作总结（上传/提交/我的/团队/详情/删除/重跑分析/范围分析/成员）
    path('work-summary/upload/', DailyWorkSummaryViewSet.as_view({'post': 'upload'}), name='work-summary-upload'),
    path('work-summary/all/', DailyWorkSummaryViewSet.as_view({'get': 'all'}), name='work-summary-all'),
    path('work-summary/config/', DailyWorkSummaryViewSet.as_view({'get': 'config', 'post': 'config'}), name='work-summary-config'),
    path('work-summary/members/', DailyWorkSummaryViewSet.as_view({'get': 'members'}), name='work-summary-members'),
    path('work-summary/range/', DailyWorkSummaryViewSet.as_view({'get': 'range', 'post': 'range'}), name='work-summary-range'),
    path('work-summary/range/<int:pk>/', DailyWorkSummaryViewSet.as_view({'get': 'range_detail'}), name='work-summary-range-detail'),
    path('work-summary/<int:pk>/', DailyWorkSummaryViewSet.as_view({'get': 'retrieve', 'delete': 'destroy'}), name='work-summary-detail'),
    path('work-summary/<int:pk>/analyze/', DailyWorkSummaryViewSet.as_view({'post': 'analyze'}), name='work-summary-analyze'),
    path('work-summary/<int:pk>/share/', DailyWorkSummaryViewSet.as_view({'post': 'share'}), name='work-summary-share'),
    path('work-summary/<int:pk>/export-pdf/', DailyWorkSummaryViewSet.as_view({'get': 'export_pdf'}), name='work-summary-export-pdf'),
    path('work-summary/', DailyWorkSummaryViewSet.as_view({'get': 'list', 'post': 'create'}), name='work-summary-list'),

    # 工作通知
    path('notifications/', WorkNotificationViewSet.as_view({'get': 'list'}), name='notification-list'),
    path('notifications/unread-count/', WorkNotificationViewSet.as_view({'get': 'unread_count'}), name='notification-unread-count'),
    path('notifications/mark-all-read/', WorkNotificationViewSet.as_view({'post': 'mark_all_read'}), name='notification-mark-all-read'),
    path('notifications/<int:pk>/mark-read/', WorkNotificationViewSet.as_view({'post': 'mark_read'}), name='notification-mark-read'),
]
