# Generated by Django 4.2.7 on 2026-04-22 01:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cloud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_md5', models.CharField(db_index=True, help_text='文件完整MD5', max_length=32)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField(help_text='文件总大小(字节)')),
                ('total_chunks', models.IntegerField(help_text='总分片数')),
                ('chunk_size', models.IntegerField(default=5242880, help_text='分片大小(默认5MB)')),
                ('uploaded_chunks', models.JSONField(default=list, help_text='已上传的分片索引列表')),
                ('uploaded_size', models.BigIntegerField(default=0, help_text='已上传字节数')),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(help_text='会话过期时间(默认24小时)')),
                ('temp_path', models.CharField(blank=True, help_text='临时分片存储目录', max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '上传会话',
                'verbose_name_plural': '上传会话',
                'indexes': [models.Index(fields=['file_md5', 'user'], name='cloud_uploa_file_md_bf1fcd_idx'), models.Index(fields=['expires_at'], name='cloud_uploa_expires_3ee6b9_idx'), models.Index(fields=['is_completed', 'updated_at'], name='cloud_uploa_is_comp_d90961_idx')],
            },
        ),
    ]
