# Generated by Django 4.2.7 on 2026-04-22 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0002_uploadsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudfile',
            name='description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='文件描述'),
        ),
        migrations.AlterField(
            model_name='cloudfile',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='标签（逗号分隔）'),
        ),
    ]
