# Generated by Django 4.2.7 on 2026-04-24 03:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cloud', '0003_alter_cloudfile_description_alter_cloudfile_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentchatmessage',
            options={'ordering': ['-created_at'], 'verbose_name': '文档聊天消息', 'verbose_name_plural': '文档聊天消息'},
        ),
        migrations.AlterModelOptions(
            name='documenteditlock',
            options={'ordering': ['-locked_at'], 'verbose_name': '文档编辑锁', 'verbose_name_plural': '文档编辑锁'},
        ),
        migrations.AlterModelOptions(
            name='filecollaboration',
            options={'ordering': ['-created_at'], 'verbose_name': '文件协作', 'verbose_name_plural': '文件协作'},
        ),
        migrations.AlterModelOptions(
            name='filecomment',
            options={'ordering': ['-created_at'], 'verbose_name': '文件评论', 'verbose_name_plural': '文件评论'},
        ),
        migrations.AlterModelOptions(
            name='fileversion',
            options={'ordering': ['-version_number', '-created_at'], 'verbose_name': '文件版本', 'verbose_name_plural': '文件版本'},
        ),
        migrations.AlterModelOptions(
            name='folder',
            options={'ordering': ['-created_at'], 'verbose_name': '文件夹', 'verbose_name_plural': '文件夹'},
        ),
        migrations.AlterModelOptions(
            name='uploadsession',
            options={'ordering': ['-created_at'], 'verbose_name': '上传会话', 'verbose_name_plural': '上传会话'},
        ),
        migrations.CreateModel(
            name='CloudSystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='配置键')),
                ('name', models.CharField(max_length=200, verbose_name='配置名称')),
                ('value', models.TextField(verbose_name='配置值')),
                ('value_type', models.CharField(choices=[('string', '文本'), ('integer', '整数'), ('float', '浮点数'), ('boolean', '布尔值'), ('json', 'JSON'), ('password', '密码')], default='string', max_length=20, verbose_name='值类型')),
                ('category', models.CharField(choices=[('basic', '基础设置'), ('onlyoffice', 'OnlyOffice 配置'), ('upload', '文件上传'), ('storage', '存储配置'), ('collaboration', '协同编辑'), ('security', '安全配置'), ('notification', '通知设置')], default='basic', max_length=50, verbose_name='配置分类')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('default_value', models.TextField(blank=True, null=True, verbose_name='默认值')),
                ('is_public', models.BooleanField(default=False, verbose_name='是否公开')),
                ('is_editable', models.BooleanField(default=True, verbose_name='是否可编辑')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='最后更新人')),
            ],
            options={
                'verbose_name': '企业网盘系统配置',
                'verbose_name_plural': '企业网盘系统配置',
                'ordering': ['category', 'key'],
                'indexes': [models.Index(fields=['category'], name='cloud_cloud_categor_944bd2_idx'), models.Index(fields=['key'], name='cloud_cloud_key_8e838d_idx'), models.Index(fields=['is_public'], name='cloud_cloud_is_publ_4f00a7_idx')],
            },
        ),
    ]
