# Generated by Django 4.2.7 on 2026-04-24 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0004_alter_documentchatmessage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudsystemconfig',
            name='onlyoffice_collaboration_mode',
            field=models.CharField(choices=[('fast', '快速模式'), ('strict', '严格模式')], default='fast', max_length=20, verbose_name='协同编辑模式'),
        ),
        migrations.AddField(
            model_name='cloudsystemconfig',
            name='onlyoffice_compact_toolbar',
            field=models.BooleanField(default=False, verbose_name='紧凑工具栏'),
        ),
        migrations.AddField(
            model_name='cloudsystemconfig',
            name='onlyoffice_document_server_url',
            field=models.CharField(default='https://chat.first-iq.com/onlyoffice', max_length=500, verbose_name='OnlyOffice 文档服务器地址'),
        ),
        migrations.AddField(
            model_name='cloudsystemconfig',
            name='onlyoffice_forcesave',
            field=models.BooleanField(default=True, verbose_name='显示强制保存按钮'),
        ),
        migrations.AddField(
            model_name='cloudsystemconfig',
            name='onlyoffice_jwt_enabled',
            field=models.BooleanField(default=True, verbose_name='启用 JWT 认证'),
        ),
        migrations.AddField(
            model_name='cloudsystemconfig',
            name='onlyoffice_jwt_secret',
            field=models.CharField(blank=True, default='voCrVp2j9QPGbzTyncEHrbakZXFN87rw', max_length=500, verbose_name='JWT 密钥'),
        ),
        migrations.AddField(
            model_name='cloudsystemconfig',
            name='onlyoffice_language',
            field=models.CharField(choices=[('zh-CN', '简体中文'), ('zh-TW', '繁体中文'), ('en-US', 'English'), ('ru-RU', 'Русский'), ('de-DE', 'Deutsch'), ('fr-FR', 'Français'), ('es-ES', 'Español'), ('pt-BR', 'Português'), ('ja-JP', '日本語'), ('ko-KR', '한국어')], default='zh-CN', max_length=10, verbose_name='界面语言'),
        ),
        migrations.AddField(
            model_name='cloudsystemconfig',
            name='onlyoffice_permission_chat',
            field=models.BooleanField(default=True, verbose_name='允许聊天'),
        ),
        migrations.AddField(
            model_name='cloudsystemconfig',
            name='onlyoffice_permission_comment',
            field=models.BooleanField(default=True, verbose_name='允许评论'),
        ),
        migrations.AddField(
            model_name='cloudsystemconfig',
            name='onlyoffice_permission_copy',
            field=models.BooleanField(default=True, verbose_name='允许复制'),
        ),
        migrations.AddField(
            model_name='cloudsystemconfig',
            name='onlyoffice_permission_download',
            field=models.BooleanField(default=True, verbose_name='允许下载'),
        ),
        migrations.AddField(
            model_name='cloudsystemconfig',
            name='onlyoffice_permission_edit',
            field=models.BooleanField(default=True, verbose_name='允许编辑'),
        ),
        migrations.AddField(
            model_name='cloudsystemconfig',
            name='onlyoffice_permission_fill_forms',
            field=models.BooleanField(default=True, verbose_name='允许填写表单'),
        ),
        migrations.AddField(
            model_name='cloudsystemconfig',
            name='onlyoffice_permission_modify_content_control',
            field=models.BooleanField(default=True, verbose_name='允许修改内容控件'),
        ),
        migrations.AddField(
            model_name='cloudsystemconfig',
            name='onlyoffice_permission_modify_filter',
            field=models.BooleanField(default=True, verbose_name='允许修改筛选器'),
        ),
        migrations.AddField(
            model_name='cloudsystemconfig',
            name='onlyoffice_permission_print',
            field=models.BooleanField(default=True, verbose_name='允许打印'),
        ),
        migrations.AddField(
            model_name='cloudsystemconfig',
            name='onlyoffice_permission_review',
            field=models.BooleanField(default=True, verbose_name='允许审阅'),
        ),
        migrations.AddField(
            model_name='cloudsystemconfig',
            name='onlyoffice_show_chat',
            field=models.BooleanField(default=True, verbose_name='显示聊天功能'),
        ),
        migrations.AddField(
            model_name='cloudsystemconfig',
            name='onlyoffice_show_comments',
            field=models.BooleanField(default=True, verbose_name='显示评论功能'),
        ),
        migrations.AddField(
            model_name='cloudsystemconfig',
            name='onlyoffice_show_review',
            field=models.BooleanField(default=True, verbose_name='显示审阅功能'),
        ),
        migrations.AddField(
            model_name='cloudsystemconfig',
            name='onlyoffice_show_spellcheck',
            field=models.BooleanField(default=True, verbose_name='启用拼写检查'),
        ),
        migrations.AddField(
            model_name='cloudsystemconfig',
            name='onlyoffice_ui_theme',
            field=models.CharField(choices=[('theme-light', '浅色主题'), ('theme-dark', '深色主题')], default='theme-light', max_length=20, verbose_name='界面主题'),
        ),
        migrations.AddField(
            model_name='cloudsystemconfig',
            name='onlyoffice_version_keep_count',
            field=models.IntegerField(default=10, verbose_name='保留版本数量'),
        ),
    ]
