# Generated by Django 4.2.7 on 2026-04-24 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0005_cloudsystemconfig_onlyoffice_collaboration_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudsystemconfig',
            name='category',
            field=models.CharField(choices=[('storage', '存储设置'), ('security', '安全设置'), ('upload', '上传设置'), ('share', '分享设置'), ('collaboration', '协同设置'), ('system', '系统设置'), ('notification', '通知设置'), ('audit', '审计日志')], db_index=True, default='system', max_length=50, verbose_name='配置分类'),
        ),
    ]
