# Generated by Django 4.2.30 on 2026-05-29 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cloud', '0006_alter_cloudsystemconfig_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOnlyOfficePermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('permission_download', models.BooleanField(default=True, verbose_name='允许下载')),
                ('permission_copy', models.BooleanField(default=True, verbose_name='允许复制')),
                ('permission_edit', models.BooleanField(default=True, verbose_name='允许编辑')),
                ('permission_print', models.BooleanField(default=True, verbose_name='允许打印')),
                ('permission_comment', models.BooleanField(default=True, verbose_name='允许评论')),
                ('permission_chat', models.BooleanField(default=True, verbose_name='允许聊天')),
                ('permission_review', models.BooleanField(default=True, verbose_name='允许审阅')),
                ('permission_fill_forms', models.BooleanField(default=True, verbose_name='允许填写表单')),
                ('permission_modify_content_control', models.BooleanField(default=True, verbose_name='允许修改内容控件')),
                ('permission_modify_filter', models.BooleanField(default=True, verbose_name='允许修改筛选')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('description', models.TextField(blank=True, null=True, verbose_name='备注说明')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_onlyoffice_permissions', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onlyoffice_permissions', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户 OnlyOffice 权限',
                'verbose_name_plural': '用户 OnlyOffice 权限',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='cloud_usero_user_id_e908fc_idx'), models.Index(fields=['is_active', '-updated_at'], name='cloud_usero_is_acti_3d0b53_idx')],
                'unique_together': {('user',)},
            },
        ),
    ]
