# Generated by Django 4.2.30 on 2026-06-03 02:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cloud', '0007_useronlyofficepermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='is_shared_folder',
            field=models.BooleanField(default=False, verbose_name='是否为共享文件夹'),
        ),
        migrations.CreateModel(
            name='FolderCollaboration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('permission', models.CharField(choices=[('read', '只读'), ('write', '可编辑'), ('admin', '管理员')], default='read', max_length=10, verbose_name='权限')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folder_collaborations', to='cloud.folder', verbose_name='共享文件夹')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folder_collaborations', to=settings.AUTH_USER_MODEL, verbose_name='协作用户')),
            ],
            options={
                'verbose_name': '共享文件夹协作',
                'verbose_name_plural': '共享文件夹协作',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['folder', 'is_active'], name='cloud_folde_folder__bfec91_idx'), models.Index(fields=['user', 'is_active'], name='cloud_folde_user_id_7ab52e_idx')],
                'unique_together': {('folder', 'user')},
            },
        ),
    ]
