# Generated by Django 4.2.30 on 2026-06-18 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0009_alter_fileoperationlog_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileoperationlog',
            name='operation',
            field=models.CharField(choices=[('create', '创建'), ('update', '更新'), ('delete', '删除'), ('restore', '恢复'), ('permanent_delete', '永久删除'), ('batch_delete', '批量删除'), ('batch_move', '批量移动'), ('move', '移动'), ('rename', '重命名'), ('upload', '上传'), ('download', '下载'), ('preview', '预览'), ('share', '分享'), ('unshare', '取消分享'), ('save_from_share', '从分享保存'), ('empty_trash', '清空回收站'), ('sync_to_cloud', '同步到云'), ('save_from_share', '从分享保存'), ('save_from_chat', '从聊天保存'), ('share_access', '分享访问'), ('edit_save', '编辑保存'), ('editing', '编辑中'), ('viewing', '查看中'), ('closed', '已关闭'), ('add_collaborator', '添加协作者'), ('update_collaborator', '更新协作者'), ('update_collaboration_status', '更新协作状态'), ('remove_collaborator', '移除协作者'), ('remove_all_collaborators', '移除所有协作者'), ('version_download', '版本下载'), ('restore_version', '恢复版本')], max_length=100, verbose_name='操作类型'),
        ),
    ]
